=head1 NAME

cwb-describe-corpus - Display information about a CWB-encoded corpora

=head1 SYNOPSIS

B<cwb-describe-corpus> [-sdh] [-r I<registry_dir>] I<corpus> ...


=head1 DESCRIPTION

B<TODO>


=head1 OPTIONS

Please note that no CWB programs currently support GNU-style C<--long-options>.

  -r <dir>  use registry directory <dir>
  -s        show statistics (attribute & lexicon size)
  -d        show details (about component files)
  -h        this help page

=over 4

=item B<TODO>

=back


=head1 SEE ALSO

L<cqp>, L<cqpserver>, L<cwb-align-encode>, L<cwb-align>, L<cwb-align-show>, L<cwb-atoi>, L<cwb-compress-rdx>, 
L<cwb-config>, L<cwb-decode-nqrfile>, L<cwb-decode>, L<cwb-encode>, L<cwb-huffcode>, 
L<cwb-itoa>, L<cwb-lexdecode>, L<cwb-makeall>, L<cwb-scan-corpus>, L<cwb-s-decode>, L<cwb-s-encode>.

=head1 COPYRIGHT

=over 4

=item
B<IMS Open Corpus Workbench (CWB)> L<http://cwb.sourceforge.net/>

=item
Copyright (C) 1993-2006 by IMS, University of Stuttgart

=item
Copyright (C) 2007- by the respective contributers (see file F<AUTHORS>)

=back

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details
(in the file F<COPYING>, or available via WWW at
L<http://www.gnu.org/copyleft/gpl.html>).

=cut

