#!/bin/bash

# Note : this is a build script, not an install script, for cross-compilation.
# So no need to run as root.


# load config.mk
config_file=$(cat config.mk)


# alter platform
target="include \$(TOP)/config/platform/darwin-universal"
rep="include \$(TOP)/config/platform/mingw"

config_file=${config_file/"$target"/"$rep"}


# alter site
target="include \$(TOP)/config/site/standard"
rep="include \$(TOP)/config/site/windows-release"

config_file=${config_file/"$target"/"$rep"}




# find out where the dlls are, and save that folder

# this is a lot easier said than done
# we need to go through the directories in the library search path of the cross-compiler,
# and if libpcre.la is there, we can try to extract its dlname= variable.
# note, this will only work for this particular crosscompiler executable!

paths=$(i586-mingw32msvc-gcc --print-search-dirs | grep "programs: =")
paths=${paths/"programs: ="/" "}
paths=$(echo $paths | tr ":" " ")

for i in $paths
do
	echo "looking in ${i}libpcre.la ......"
	if [ -f "${i}libpcre.la" ] ; then
		echo "found!"
		LIBPRCE_LA=$(cat "${i}libpcre.la")
		LIBPCRE_LA_FOUND_IN=$i 
		break
	fi
done

# echo "$LIBPRCE_LA"

if [ -n $LIBPCRE_LA ] ; then 
	echo " "
else 
	echo "Couldn't find libpcre.la!! Script aborts"
	exit
fi

# echo "-----------> $LIBPCRE_LA" 

DLNAME_LINE=$(grep "^dlname='" < "${LIBPCRE_LA_FOUND_IN}libpcre.la")
echo "dlname line == $DLNAME_LINE"
DLNAME_LINE=$(echo $DLNAME_LINE | tr -d "'")
dlname=${DLNAME_LINE/"dlname="/""}


echo "$LIBPCRE_LA_FOUND_IN$dlname"
deduced_path=$(dirname $LIBPCRE_LA_FOUND_IN$dlname)
deduced_path=$(cd "$deduced_path" && pwd)

echo "Deduced path to DLLS as $deduced_path..... "


append=$( cat <<HERE

LIBPCRE_DLL_PATH=$deduced_path



HERE
)

config_file="$append
$config_file" 

# save config.mk
rm -f config.mk.bak
mv config.mk config.mk.bak
echo "$config_file" > config.mk

if [ -f config.mk ] ; then echo "config.mk exists" ; else echo "config.mk doesn't exist" ; exit ; fi
if [ -f config.mk.bak ] ; then echo "config.mk.bak exists" ; else echo "config.mk.bak doesn't exist" ; exit ; fi

# make cwb

make clean
make depend
make cl
make mingw-libgnurx-2.5.1
make utils
make cqp

# and finally....

LIBPCRE_DLL_PATH=$deduced_path && make release

# restore original state of config file (so subversion doesn't get confused if this is a checked-out version)
rm config.mk
mv config.mk.bak config.mk
