CWB: utils/barlib.c File Reference
barlib.c File Reference
#include "barlib.h"
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
Functions
BARdesc BAR_new (int N, int M, int W)
void BAR_reinit (BARdesc BAR, int N, int M, int W)
void BAR_delete (BARdesc BAR)
void BAR_write (BARdesc BAR, int x, int y, int i)
int BAR_read (BARdesc BAR, int x, int y)
Function Documentation
void BAR_delete (BARdesc BAR)
References _BARdesc::d_block_data, _BARdesc::d_block_start_x, and _BARdesc::data.
Referenced by best_path().
BARdesc BAR_new (int N, int M, int W)
References _BARdesc::beam_width, _BARdesc::d_block_data, _BARdesc::d_block_start_x, _BARdesc::d_size, _BARdesc::data, _BARdesc::data_size, _BARdesc::vector_size, _BARdesc::x_size, and _BARdesc::y_size.
Referenced by best_path().
int BAR_read (BARdesc BAR, int x, int y)
References _BARdesc::beam_width, _BARdesc::d_block_data, and _BARdesc::d_block_start_x.
Referenced by best_path().
void BAR_reinit (BARdesc BAR, int N, int M, int W)
References _BARdesc::beam_width, _BARdesc::d_block_data, _BARdesc::d_block_start_x, _BARdesc::d_size, _BARdesc::data, _BARdesc::data_size, _BARdesc::vector_size, _BARdesc::x_size, and _BARdesc::y_size.
void BAR_write (BARdesc BAR, int x, int y, int i)
References beam_width, _BARdesc::beam_width, _BARdesc::d_block_data, and _BARdesc::d_block_start_x.
Referenced by best_path().