CWB: cl/binsert.h File Reference
binsert.h File Reference
Defines
#define _BINSERT_H_
Functions
void * binsert_g (const void *key, void **base, size_t *nel, size_t size, int(*compar)(const void *, const void *))
Define Documentation
#define _BINSERT_H_
Function Documentation
void* binsert_g (const void * key, void ** base, size_t * nel, size_t size, int(*)(const void *, const void *) compar)
References cl_malloc(), cl_realloc(), and REALLOC_THRESHOLD.
Referenced by ComputeGroupInternally().