CWB: cqp/cqp.c File Reference
cqp.c File Reference
#include <stdio.h>
#include <signal.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/time.h>
#include "../cl/globals.h"
#include "../cl/macros.h"
#include "cqp.h"
#include "options.h"
#include "output.h"
#include "symtab.h"
#include "tree.h"
#include "eval.h"
#include "corpmanag.h"
#include "regex2dfa.h"
#include "ranges.h"
#include "macro.h"
#include "targets.h"
#include "parser.tab.h"
Functions
int yyparse (void)
Activates the CQP-query-language parser.
void yyrestart (FILE *input_file)
restarts the CQP-query-language parser.
static void sigINT_signal_handler (int signum)
This is the signal handler function that is used for the interrupt signal (CTRL+C).
void install_signal_handler (void)
Installs the interrupt signal handler function with the OS.
int initialize_cqp (int argc, char **argv)
Initialises the CQP program (or cqpserver or cqpcl).
int cqp_parse_file (FILE *fd, int exit_on_parse_errors)
Parses a stream for CQP query syntax.
int cqp_parse_string (char *s)
Parses a string for CQP query syntax.
int setInterruptCallback (InterruptCheckProc f)
Sets the interrupt callback function.
void CheckForInterrupts (void)
Calls the interrupt callback function, if set.
Variables
FILE * yyin
File handle used by the CQP-query-language parser.
FILE * cqp_files [MAXCQPFILES]
Array of file handles.
int cqp_file_p
index-pointer into cqp_files.
int reading_cqprc = 0
Boolean: true iff cqp_parse_file() - the main query syntax parsing function - is currently reading from the cqprc file handler.
char QueryBuffer [QUERY_BUFFER_SIZE]
buffer for queries
int QueryBufferP = 0
pointer into this buffer, for appending
int QueryBufferOverflow = 0
flag which signals buffer overflows
InterruptCheckProc interruptCallbackHook = NULL
Pointer for the interrupt callback function.
Function Documentation
void CheckForInterrupts (void)
Calls the interrupt callback function, if set.
References interruptCallbackHook.
Referenced by evaluate_target(), and simulate().
int cqp_parse_file (FILE * fd, int exit_on_parse_errors)
Parses a stream for CQP query syntax.
Note that cqp_parse_file() fclose()s fd unless it is STDOUT.
Parameters:
fd File handle of the file to parse.
exit_on_parse_errors Boolean: should CQP exit on parse errors?
Returns:
Boolean: true = all ok, false = a problem.
References child_process, cqp_file_p, cqp_files, current_corpus, exit_cqp, MAXCQPFILES, cl::mother_name, cl::name, NULL, quiet, reading_cqprc, save_on_exit, save_unsaved_subcorpora(), silent, cl::size, STREQ, yyin, yyparse, and yyrestart.
Referenced by do_exec(), initialize_cqp(), and main().
int cqp_parse_string (char * s)
Parses a string for CQP query syntax.
Parameters:
s The string to parse.
Returns:
Boolean: true = all ok, false = a problem.
References cqp_input_string, cqp_input_string_position, cqpmessage(), cqpserver, Error, exit_cqp, which_app, and yyparse.
Referenced by do_cqi_cqp_query(), and main().
int initialize_cqp (int argc, char ** argv)
Initialises the CQP program (or cqpserver or cqpcl).
This function:
initialises the global variables;
initialises the built-in random number generator;
initialises the macro database;
parses the program options;
reads the initialisation file;
reads the macro initialisation file;
and loads the default corpus, if any.
Parameters:
argc The argc from main()
argv The argv from main()
Returns:
Always 1.
References batchfd, batchmode, check_available_corpora(), child_process, cl_randomize(), corpuslist, cqp_file_p, cqp_init_file, cqp_parse_file(), CQPMACRORC_NAME, cqpmessage(), CQPRC_NAME, cqpserver, default_corpus, eep, enable_macros, exit_cqp, init_macros(), macro_init_file, NULL, parse_options(), parser_debug, reading_cqprc, set_current_corpus_name(), SUBDIR_SEPARATOR, UNDEF, Warning, which_app, and yydebug.
Referenced by main().
void install_signal_handler (void)
Installs the interrupt signal handler function with the OS.
This function installs a Ctrl-C interrupt handler (clears EvaluationIsRunning flag). The function installed is sigINT_signal_handler.
See also:
sigINT_signal_handler
References cqpmessage(), sigINT_signal_handler(), signal_handler_is_installed, and Warning.
Referenced by check_alignment_constraints(), ComputeGroupInternally(), evaluate_subset(), evaluate_target(), main(), simulate_dfa(), SortSubcorpus(), and SortSubcorpusRandomize().
int setInterruptCallback (InterruptCheckProc f)
Sets the interrupt callback function.
Parameters:
f Pointer to the function to set as interrupt callback.
Returns:
Always 1.
References interruptCallbackHook.
static void sigINT_signal_handler (int signum) [static]
This is the signal handler function that is used for the interrupt signal (CTRL+C).
Parameters:
signum The signal number (ignored).
References EvaluationIsRunning, and signal_handler_is_installed.
Referenced by install_signal_handler().
int yyparse (void)
Activates the CQP-query-language parser.
References access_corpus(), ActivateCorpus(), add_corpus_property(), add_grant_to_last_user(), add_host_to_list(), add_hosts_in_subnet_to_list(), add_tabular_pattern(), add_user_to_list(), addHistoryLine(), TCorpus::admin, after_CorpusCommand(), after_CorpusSetExpr(), after_Query(), YYSTYPE::Anchor, Anchor, YYSTYPE::AnchorPair, _Attribute::any, YYSTYPE::apl, append_tabulation_item(), YYSTYPE::args, ATT_ALIGN, ATT_DYN, ATT_POS, ATT_STRUC, YYSTYPE::attr, ctxtsp::attrib, TCorpus::attributes, YYSTYPE::AttributeSpecification, autoshow, YYSTYPE::base, bool_and(), bool_implies(), bool_not(), bool_or(), YYSTYPE::boolo, YYSTYPE::boolt, catalog_corpus(), CD, TCorpus::charset, YYSTYPE::cl, cl_free, cl_malloc(), cl_randomize(), cl_set_seed(), cl_strdup(), cmp_eq, cmp_get, cmp_gt, cmp_let, cmp_lt, cmp_neq, cnode, CompCorpus, CompCorpusFreqs, CompDirectory, CompLexicon, CompLexiconIdx, CompLexiconSrt, CompRevCorpus, CompRevCorpusIdx, YYSTYPE::context, cqpmessage(), cregerror, cregerror_cleanup(), cregestring, cregSetAttrComponentPath, CurEnv, current_corpus, declare_default_components(), define_macro(), YYSTYPE::direction, ctxtsp::direction, YYSTYPE::Distance, do_AddSubVariables(), do_AnchorPoint(), do_attribute_show(), do_cat(), do_cut(), do_delete_lines(), do_delete_lines_num(), do_Description(), do_dump(), do_exec(), do_flagged_re_variable(), do_flagged_string(), do_group(), do_group2(), do_IDReference(), do_info(), do_LabelReference(), do_MeetStatement(), do_MUQuery(), do_mval_string(), do_NamedWfPattern(), do_OptDistance(), do_PrintAllVariables(), do_printVariableSize(), do_PrintVariableValue(), do_reduce(), do_RelExExpr(), do_RelExpr(), do_save(), do_SearchPattern(), do_set_complex_target(), do_set_target(), do_setop(), do_SetVariableValue(), do_SimpleVariableReference(), do_size(), do_sleep(), do_StandardQuery(), do_start_timer(), do_StringConstraint(), do_StructuralContext(), do_subset(), do_TABQuery(), do_timing(), do_undump(), do_UnionStatement(), do_WordformPattern(), do_XMLTag(), drop_temp_corpora(), dropcorpus(), enable_macros, Error, YYSTYPE::evalt, exit_cqp, expansion, YYSTYPE::field, field_type_to_name(), find_option(), findcorpus(), FindVariable(), _TabulationItem::flags, float_leaf, free_tabulation_list(), FreeSortClause(), FunctionCall(), generate_code, GlobalPrintMode, TCorpus::groupAccessList, hard_boundary, TCorpus::hostAccessList, TCorpus::id, YYSTYPE::idlist, IGNORE_REGEX, in_CorpusCommand(), YYSTYPE::in_redir, in_UnnamedCorpusCommand(), YYSTYPE::index, TCorpus::info_file, int_leaf, YYSTYPE::ival, KeywordField, LAB_DEFINED, labellookup(), evalenv::labels, last, leaf, left, leftright, list_macros(), load_macro_file(), make_first_tabular_pattern(), makearg(), evalenv::match_label, evalenv::matchend_label, MatchEndField, MatchField, Message, mode, TCorpus::name, evalenv::negated, New, NEW_BNODE, NEW_EVALLEAF, NEW_EVALNODE, new_tabulation_item(), _ActualParamList::next, _idbuf::next, _DynArg::next, TCorpus::next, next_environment(), node, NoField, TCorpus::nr_of_loads, NULL, old_query_corpus, OP_CONTAINS, OP_EQUAL, OP_MATCHES, OP_NOT, TCorpus::path, prepare_AlignmentConstraints(), prepare_do_subset(), prepare_input(), prepare_parse(), prepare_Query(), print_macro_definition(), print_option_value(), print_option_values(), print_tabulation(), PrintContextDescriptor(), TCorpus::properties, query_corpus, query_lock, RangeSetop(), RDiff, re_repeat, YYSTYPE::redir, reg_disj(), reg_seq(), TCorpus::registry_dir, TCorpus::registry_name, repeat_inf, resetQueryBuffer(), right, RIntersection, RMaximalMatches, YYSTYPE::rngsetop, RUnion, evalenv::search_context, SELECTED_LINES, set_context_option_value(), set_integer_option_value(), set_string_option_value(), setup_attribute(), show_corpora_files(), ctxtsp::size, size2, YYSTYPE::sortclause, SortSubcorpus(), SortSubcorpusRandomize(), YYSTYPE::storage, _idbuf::string, YYSTYPE::strval, SUB, synchronize(), SYSTEM, YYSTYPE::tabulation_item, TargetField, ctxtsp::type, UNDEF, UNSELECTED_LINES, TCorpus::userAccessList, var_ref, YYSTYPE::varsetting, YYSTYPE::varval, warn_query_lock_violation(), Warning, within_gc, word, YY_, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror, YYFINAL, YYID, YYLAST, YYMAXDEPTH, YYPACT_NINF, YYPOPSTACK, YYSIZE_T, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_ALLOC_MAXIMUM, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, YYTABLE_NINF, YYTERROR, YYTRANSLATE, and yyalloc::yyvs_alloc.
void yyrestart (FILE * input_file)
restarts the CQP-query-language parser.
Variable Documentation
int cqp_file_p
index-pointer into cqp_files.
See also:
cqp_files
Referenced by cqp_parse_file(), and initialize_cqp().
FILE* cqp_files[MAXCQPFILES]
Array of file handles.
Allows nested execution of "included" text files full of commands.
Referenced by cqp_parse_file().
InterruptCheckProc interruptCallbackHook = NULL
Pointer for the interrupt callback function.
Referenced by CheckForInterrupts(), and setInterruptCallback().
char QueryBuffer[QUERY_BUFFER_SIZE]
buffer for queries
Referenced by addHistoryLine(), after_CorpusCommand(), after_Query(), prepare_Query(), resetQueryBuffer(), yy_input_char(), and yyerror().
int QueryBufferOverflow = 0
flag which signals buffer overflows
Referenced by after_CorpusCommand(), after_Query(), resetQueryBuffer(), and yy_input_char().
int QueryBufferP = 0
pointer into this buffer, for appending
Referenced by after_Query(), resetQueryBuffer(), and yy_input_char().
int reading_cqprc = 0
Boolean: true iff cqp_parse_file() - the main query syntax parsing function - is currently reading from the cqprc file handler.
See also:
cqprc
cqp_parse_file
Referenced by addHistoryLine(), cqp_parse_file(), initialize_cqp(), and yy_input_char().
FILE* yyin
File handle used by the CQP-query-language parser.