CWB: cqp/parser.tab.c File Reference
parser.tab.c File Reference
#include <sys/time.h>
#include <sys/resource.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>
#include <assert.h>
#include <stdarg.h>
#include <stdlib.h>
#include "../cl/globals.h"
#include "../cl/special-chars.h"
#include "../cl/attributes.h"
#include "../cl/macros.h"
#include "cqp.h"
#include "options.h"
#include "ranges.h"
#include "symtab.h"
#include "treemacros.h"
#include "tree.h"
#include "eval.h"
#include "corpmanag.h"
#include "regex2dfa.h"
#include "builtins.h"
#include "groups.h"
#include "targets.h"
#include "attlist.h"
#include "concordance.h"
#include "output.h"
#include "print-modes.h"
#include "variables.h"
#include "parse_actions.h"
#include "../CQi/auth.h"
#include "macro.h"
Data Structures
union YYSTYPE
union yyalloc
Defines
#define YYBISON 1
#define YYBISON_VERSION "2.4.1"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 0
#define YYPUSH 0
#define YYPULL 1
#define YYLSP_NEEDED 0
#define YYERROR_VERBOSE
#define YYDEBUG 1
#define YYERROR_VERBOSE 0
#define YYTOKEN_TABLE 0
#define YYTOKENTYPE
#define YYSTYPE_IS_TRIVIAL 1
#define yystype YYSTYPE
#define YYSTYPE_IS_DECLARED 1
#define YYSIZE_T unsigned int
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YY_(msgid) msgid
#define YYUSE(e) ((void) (e))
#define YYID(n) (n)
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYMALLOC malloc
#define YYFREE free
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY(To, From, Count)
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYFINAL 4
#define YYLAST 478
#define YYNTOKENS 121
#define YYNNTS 137
#define YYNRULES 325
#define YYNSTATES 492
#define YYUNDEFTOK 2
#define YYMAXUTOK 353
#define YYTRANSLATE(YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF -300
#define YYTABLE_NINF -324
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYFAIL goto yyerrlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYRHSLOC(Rhs, K) ((Rhs)[K])
#define YYLLOC_DEFAULT(Current, Rhs, N)
#define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#define YYLEX yylex ()
#define YYDPRINTF(Args)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
Typedefs
typedef union YYSTYPE YYSTYPE
typedef unsigned char yytype_uint8
typedef short int yytype_int8
typedef unsigned short int yytype_uint16
typedef short int yytype_int16
Enumerations
enum yytokentype {
NAME_SYM = 258, ID_SYM = 259, INFO_SYM = 260, HOME_SYM = 261,
ATTRIBUTE_SYM = 262, DIR_SYM = 263, CORPUS_SYM = 264, REVCORP_SYM = 265,
REVCIDX_SYM = 266, FREQS_SYM = 267, LEXICON_SYM = 268, LEXIDX_SYM = 269,
LEXSRT_SYM = 270, STRUCTURE_SYM = 271, ALIGNED_SYM = 272, DYNAMIC_SYM = 273,
DOTS_SYM = 274, IGNORE_SYM = 275, ADMIN_SYM = 276, ACCESS_SYM = 277,
USER_SYM = 278, GROUP_SYM = 279, ASSERT_SYM = 280, HOST_SYM = 281,
PROPERTY_SYM = 282, IDENTIFIER = 283, STRING = 284, NUMBER = 285,
NAME_SYM = 258, ID_SYM = 259, INFO_SYM = 260, HOME_SYM = 261,
ATTRIBUTE_SYM = 262, DIR_SYM = 263, CORPUS_SYM = 264, REVCORP_SYM = 265,
REVCIDX_SYM = 266, FREQS_SYM = 267, LEXICON_SYM = 268, LEXIDX_SYM = 269,
LEXSRT_SYM = 270, STRUCTURE_SYM = 271, ALIGNED_SYM = 272, DYNAMIC_SYM = 273,
DOTS_SYM = 274, IGNORE_SYM = 275, ADMIN_SYM = 276, ACCESS_SYM = 277,
USER_SYM = 278, GROUP_SYM = 279, ASSERT_SYM = 280, HOST_SYM = 281,
PROPERTY_SYM = 282, IDENTIFIER = 283, STRING = 284, NUMBER = 285,
ID = 258, QID = 259, LABEL = 260, STRING = 261,
FLAG = 262, TAGSTART = 263, TAGEND = 264, VARIABLE = 265,
IPAddress = 266, IPSubnet = 267, INTEGER = 268, DOUBLEFLOAT = 269,
FIELD = 270, FIELDLABEL = 271, ANCHORTAG = 272, ANCHORENDTAG = 273,
SEARCH_STRATEGY = 274, TAB_SYM = 275, CAT_SYM = 276, DEFINE_SYM = 277,
DIFF_SYM = 278, DISCARD_SYM = 279, EXPAND_SYM = 280, EXIT_SYM = 281,
FLAT_SYM = 282, INTER_SYM = 283, JOIN_SYM = 284, SUBSET_SYM = 285,
LEFT_SYM = 286, RIGHT_SYM = 287, SAVE_SYM = 288, SCATTER_SYM = 289,
SHOW_SYM = 290, CD_SYM = 291, TO_SYM = 292, WITHIN_SYM = 293,
SET_SYM = 294, EXEC_SYM = 295, CUT_SYM = 296, OCCURS_SYM = 297,
INFO_SYM = 298, GROUP_SYM = 299, WHERE_SYM = 300, ESCAPE_SYM = 301,
MEET_SYM = 302, UNION_SYM = 303, MU_SYM = 304, SORT_SYM = 305,
COUNT_SYM = 306, ASC_SYM = 307, DESC_SYM = 308, REVERSE_SYM = 309,
BY_SYM = 310, FOREACH_SYM = 311, ON_SYM = 312, YES_SYM = 313,
OFF_SYM = 314, NO_SYM = 315, SLEEP_SYM = 316, REDUCE_SYM = 317,
MAXIMAL_SYM = 318, WITH_SYM = 319, WITHOUT_SYM = 320, DELETE_SYM = 321,
SIZE_SYM = 322, DUMP_SYM = 323, UNDUMP_SYM = 324, TABULATE_SYM = 325,
NOT_SYM = 326, CONTAINS_SYM = 327, MATCHES_SYM = 328, GCDEL = 329,
APPEND = 330, LET = 331, GET = 332, NEQ = 333,
IMPLIES = 334, RE_PAREN = 335, EOL_SYM = 336, ELLIPSIS = 337,
MATCHALL = 338, LCSTART = 339, LCEND = 340, LCMATCHALL = 341,
PLUSEQ = 342, MINUSEQ = 343, UNLOCK_SYM = 344, USER_SYM = 345,
HOST_SYM = 346, UNDEFINED_MACRO = 347, MACRO_SYM = 348, RANDOMIZE_SYM = 349,
FROM_SYM = 350, INCLUSIVE_SYM = 351, EXCLUSIVE_SYM = 352, NULL_SYM = 353,
ID = 258, QID = 259, LABEL = 260, STRING = 261,
FLAG = 262, TAGSTART = 263, TAGEND = 264, VARIABLE = 265,
IPAddress = 266, IPSubnet = 267, INTEGER = 268, DOUBLEFLOAT = 269,
FIELD = 270, FIELDLABEL = 271, ANCHORTAG = 272, ANCHORENDTAG = 273,
SEARCH_STRATEGY = 274, TAB_SYM = 275, CAT_SYM = 276, DEFINE_SYM = 277,
DIFF_SYM = 278, DISCARD_SYM = 279, EXPAND_SYM = 280, EXIT_SYM = 281,
FLAT_SYM = 282, INTER_SYM = 283, JOIN_SYM = 284, SUBSET_SYM = 285,
LEFT_SYM = 286, RIGHT_SYM = 287, SAVE_SYM = 288, SCATTER_SYM = 289,
SHOW_SYM = 290, CD_SYM = 291, TO_SYM = 292, WITHIN_SYM = 293,
SET_SYM = 294, EXEC_SYM = 295, CUT_SYM = 296, OCCURS_SYM = 297,
INFO_SYM = 298, GROUP_SYM = 299, WHERE_SYM = 300, ESCAPE_SYM = 301,
MEET_SYM = 302, UNION_SYM = 303, MU_SYM = 304, SORT_SYM = 305,
COUNT_SYM = 306, ASC_SYM = 307, DESC_SYM = 308, REVERSE_SYM = 309,
BY_SYM = 310, FOREACH_SYM = 311, ON_SYM = 312, YES_SYM = 313,
OFF_SYM = 314, NO_SYM = 315, SLEEP_SYM = 316, REDUCE_SYM = 317,
MAXIMAL_SYM = 318, WITH_SYM = 319, WITHOUT_SYM = 320, DELETE_SYM = 321,
SIZE_SYM = 322, DUMP_SYM = 323, UNDUMP_SYM = 324, TABULATE_SYM = 325,
NOT_SYM = 326, CONTAINS_SYM = 327, MATCHES_SYM = 328, GCDEL = 329,
APPEND = 330, LET = 331, GET = 332, NEQ = 333,
IMPLIES = 334, RE_PAREN = 335, EOL_SYM = 336, ELLIPSIS = 337,
MATCHALL = 338, LCSTART = 339, LCEND = 340, LCMATCHALL = 341,
PLUSEQ = 342, MINUSEQ = 343, UNLOCK_SYM = 344, USER_SYM = 345,
HOST_SYM = 346, UNDEFINED_MACRO = 347, MACRO_SYM = 348, RANDOMIZE_SYM = 349,
FROM_SYM = 350, INCLUSIVE_SYM = 351, EXCLUSIVE_SYM = 352, NULL_SYM = 353
}
Functions
int yylex (void)
void yyerror (char *s)
void warn_query_lock_violation (void)
void synchronize (void)
static void yydestruct (char *yymsg, int yytype, YYSTYPE *yyvaluep) const
int yyparse ()
Activates the CQP-query-language parser.
Variables
int yychar
static const yytype_uint8 yytranslate []
static const yytype_uint16 yyr1 []
static const yytype_uint8 yyr2 []
static const yytype_uint16 yydefact []
static const yytype_int16 yydefgoto []
static const yytype_int16 yypact []
static const yytype_int16 yypgoto []
static const yytype_int16 yytable []
static const yytype_uint16 yycheck []
static const yytype_uint16 yystos []
YYSTYPE yylval
int yynerrs
Define Documentation
#define YY_ (msgid) msgid
Referenced by yyparse().
#define YY_LOCATION_PRINT (File, Loc) ((void) 0)
#define YY_REDUCE_PRINT (Rule)
Referenced by yyparse().
#define YY_STACK_PRINT (Bottom, Top)
Referenced by yyparse().
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Referenced by yydestruct(), and yyparse().
#define YYABORT goto yyabortlab
#define YYACCEPT goto yyacceptlab
#define YYBACKUP (Token, Value)
Value:
do                \
  if (yychar == YYEMPTY && yylen == 1)        \
    {               \
      yychar = (Token);           \
      yylval = (Value);           \
      yytoken = YYTRANSLATE (yychar);       \
      YYPOPSTACK (1);           \
      goto yybackup;            \
    }               \
  else                \
    {               \
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;              \
    }               \
while (YYID (0))
#define YYBISON 1
#define YYBISON_VERSION "2.4.1"
#define yyclearin (yychar = YYEMPTY)
#define YYCOPY (To, From, Count)
Value:
do          \
  {         \
    YYSIZE_T yyi;       \
    for (yyi = 0; yyi < (Count); yyi++) \
      (To)[yyi] = (From)[yyi];    \
  }         \
      while (YYID (0))
#define YYDEBUG 1
#define YYDPRINTF (Args)
Referenced by yyparse().
#define YYEMPTY (-2)
Referenced by yyparse().
#define YYEOF 0
Referenced by yyparse().
#define YYERRCODE 256
#define yyerrok (yyerrstatus = 0)
#define YYERROR goto yyerrorlab
#define YYERROR_VERBOSE
#define YYERROR_VERBOSE 0
#define YYFAIL goto yyerrlab
#define YYFINAL 4
Referenced by yyparse().
#define YYFREE free
#define YYID (n) (n)
Referenced by yyparse().
#define YYINITDEPTH 200
#define YYLAST 478
Referenced by yyparse().
#define YYLEX yylex ()
#define YYLLOC_DEFAULT (Current, Rhs, N)
Value:
do                  \
      if (YYID (N))                                                    \
  {               \
    (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;  \
    (Current).first_column = YYRHSLOC (Rhs, 1).first_column;  \
    (Current).last_line    = YYRHSLOC (Rhs, N).last_line;   \
    (Current).last_column  = YYRHSLOC (Rhs, N).last_column; \
  }               \
      else                \
  {               \
    (Current).first_line   = (Current).last_line   =    \
      YYRHSLOC (Rhs, 0).last_line;        \
    (Current).first_column = (Current).last_column =    \
      YYRHSLOC (Rhs, 0).last_column;        \
  }               \
    while (YYID (0))
#define YYLSP_NEEDED 0
#define YYMALLOC malloc
#define YYMAXDEPTH 10000
Referenced by yyparse().
#define YYMAXUTOK 353
#define YYNNTS 137
#define YYNRULES 325
#define YYNSTATES 492
#define YYNTOKENS 121
#define YYPACT_NINF -300
Referenced by yyparse().
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
#define YYPULL 1
#define YYPURE 0
#define YYPUSH 0
#define YYRECOVERING () (!!yyerrstatus)
#define YYRHSLOC (Rhs, K) ((Rhs)[K])
#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)
#define YYSIZE_T unsigned int
Referenced by yyparse().
#define YYSKELETON_NAME "yacc.c"
#define YYSTACK_ALLOC YYMALLOC
Referenced by yyparse().
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
Referenced by yyparse().
#define YYSTACK_BYTES (N)
Value:
((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Referenced by yyparse().
#define YYSTACK_FREE YYFREE
Referenced by yyparse().
#define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
do                  \
      {                 \
  YYSIZE_T yynewbytes;            \
  YYCOPY (&yyptr->Stack_alloc, Stack, yysize);      \
  Stack = &yyptr->Stack_alloc;          \
  yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
  yyptr += yynewbytes / sizeof (*yyptr);        \
      }                 \
    while (YYID (0))
Referenced by yyparse().
#define yystype YYSTYPE
#define YYSTYPE_IS_DECLARED 1
#define YYSTYPE_IS_TRIVIAL 1
#define YYTABLE_NINF -324
Referenced by yyparse().
#define YYTERROR 1
Referenced by yyparse().
#define YYTOKEN_TABLE 0
#define YYTOKENTYPE
#define YYTRANSLATE (YYX) ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Referenced by yyparse().
#define YYUNDEFTOK 2
#define YYUSE (e) ((void) (e))
Referenced by yydestruct().
Typedef Documentation
typedef union YYSTYPE YYSTYPE
typedef short int yytype_int16
typedef short int yytype_int8
typedef unsigned short int yytype_uint16
typedef unsigned char yytype_uint8
Enumeration Type Documentation
enum yytokentype
Enumerator:
NAME_SYM
ID_SYM
INFO_SYM
HOME_SYM
ATTRIBUTE_SYM
DIR_SYM
CORPUS_SYM
REVCORP_SYM
REVCIDX_SYM
FREQS_SYM
LEXICON_SYM
LEXIDX_SYM
LEXSRT_SYM
STRUCTURE_SYM
ALIGNED_SYM
DYNAMIC_SYM
DOTS_SYM
IGNORE_SYM
ADMIN_SYM
ACCESS_SYM
USER_SYM
GROUP_SYM
ASSERT_SYM
HOST_SYM
PROPERTY_SYM
IDENTIFIER
STRING
NUMBER
NAME_SYM
ID_SYM
INFO_SYM
HOME_SYM
ATTRIBUTE_SYM
DIR_SYM
CORPUS_SYM
REVCORP_SYM
REVCIDX_SYM
FREQS_SYM
LEXICON_SYM
LEXIDX_SYM
LEXSRT_SYM
STRUCTURE_SYM
ALIGNED_SYM
DYNAMIC_SYM
DOTS_SYM
IGNORE_SYM
ADMIN_SYM
ACCESS_SYM
USER_SYM
GROUP_SYM
ASSERT_SYM
HOST_SYM
PROPERTY_SYM
IDENTIFIER
STRING
NUMBER
ID
QID
LABEL
STRING
FLAG
TAGSTART
TAGEND
VARIABLE
IPAddress
IPSubnet
INTEGER
DOUBLEFLOAT
FIELD
FIELDLABEL
ANCHORTAG
ANCHORENDTAG
SEARCH_STRATEGY
TAB_SYM
CAT_SYM
DEFINE_SYM
DIFF_SYM
DISCARD_SYM
EXPAND_SYM
EXIT_SYM
FLAT_SYM
INTER_SYM
JOIN_SYM
SUBSET_SYM
LEFT_SYM
RIGHT_SYM
SAVE_SYM
SCATTER_SYM
SHOW_SYM
CD_SYM
TO_SYM
WITHIN_SYM
SET_SYM
EXEC_SYM
CUT_SYM
OCCURS_SYM
INFO_SYM
GROUP_SYM
WHERE_SYM
ESCAPE_SYM
MEET_SYM
UNION_SYM
MU_SYM
SORT_SYM
COUNT_SYM
ASC_SYM
DESC_SYM
REVERSE_SYM
BY_SYM
FOREACH_SYM
ON_SYM
YES_SYM
OFF_SYM
NO_SYM
SLEEP_SYM
REDUCE_SYM
MAXIMAL_SYM
WITH_SYM
WITHOUT_SYM
DELETE_SYM
SIZE_SYM
DUMP_SYM
UNDUMP_SYM
TABULATE_SYM
NOT_SYM
CONTAINS_SYM
MATCHES_SYM
GCDEL
APPEND
LET
GET
NEQ
IMPLIES
RE_PAREN
EOL_SYM
ELLIPSIS
MATCHALL
LCSTART
LCEND
LCMATCHALL
PLUSEQ
MINUSEQ
UNLOCK_SYM
USER_SYM
HOST_SYM
UNDEFINED_MACRO
MACRO_SYM
RANDOMIZE_SYM
FROM_SYM
INCLUSIVE_SYM
EXCLUSIVE_SYM
NULL_SYM
ID
QID
LABEL
STRING
FLAG
TAGSTART
TAGEND
VARIABLE
IPAddress
IPSubnet
INTEGER
DOUBLEFLOAT
FIELD
FIELDLABEL
ANCHORTAG
ANCHORENDTAG
SEARCH_STRATEGY
TAB_SYM
CAT_SYM
DEFINE_SYM
DIFF_SYM
DISCARD_SYM
EXPAND_SYM
EXIT_SYM
FLAT_SYM
INTER_SYM
JOIN_SYM
SUBSET_SYM
LEFT_SYM
RIGHT_SYM
SAVE_SYM
SCATTER_SYM
SHOW_SYM
CD_SYM
TO_SYM
WITHIN_SYM
SET_SYM
EXEC_SYM
CUT_SYM
OCCURS_SYM
INFO_SYM
GROUP_SYM
WHERE_SYM
ESCAPE_SYM
MEET_SYM
UNION_SYM
MU_SYM
SORT_SYM
COUNT_SYM
ASC_SYM
DESC_SYM
REVERSE_SYM
BY_SYM
FOREACH_SYM
ON_SYM
YES_SYM
OFF_SYM
NO_SYM
SLEEP_SYM
REDUCE_SYM
MAXIMAL_SYM
WITH_SYM
WITHOUT_SYM
DELETE_SYM
SIZE_SYM
DUMP_SYM
UNDUMP_SYM
TABULATE_SYM
NOT_SYM
CONTAINS_SYM
MATCHES_SYM
GCDEL
APPEND
LET
GET
NEQ
IMPLIES
RE_PAREN
EOL_SYM
ELLIPSIS
MATCHALL
LCSTART
LCEND
LCMATCHALL
PLUSEQ
MINUSEQ
UNLOCK_SYM
USER_SYM
HOST_SYM
UNDEFINED_MACRO
MACRO_SYM
RANDOMIZE_SYM
FROM_SYM
INCLUSIVE_SYM
EXCLUSIVE_SYM
NULL_SYM
Function Documentation
void synchronize (void)
References cqp_input_string, delete_macro_buffers(), enable_macros, NULL, yychar, and yylex.
Referenced by yyparse().
void warn_query_lock_violation (void)
References cqpserver, query_lock_violation, and which_app.
Referenced by yyparse().
static void yydestruct (char * yymsg, int yytype, YYSTYPE * yyvaluep) const [static]
References YY_SYMBOL_PRINT, and YYUSE.
Referenced by yyparse().
void yyerror (char * s)
References cqpmessage(), Error, generate_code, and QueryBuffer.
Referenced by yyparse().
int yylex (void)
int yyparse (void)
Activates the CQP-query-language parser.
References access_corpus(), ActivateCorpus(), add_corpus_property(), add_grant_to_last_user(), add_host_to_list(), add_hosts_in_subnet_to_list(), add_tabular_pattern(), add_user_to_list(), addHistoryLine(), TCorpus::admin, after_CorpusCommand(), after_CorpusSetExpr(), after_Query(), YYSTYPE::Anchor, Anchor, YYSTYPE::AnchorPair, _Attribute::any, YYSTYPE::apl, append_tabulation_item(), YYSTYPE::args, ATT_ALIGN, ATT_DYN, ATT_POS, ATT_STRUC, YYSTYPE::attr, ctxtsp::attrib, TCorpus::attributes, YYSTYPE::AttributeSpecification, autoshow, YYSTYPE::base, bool_and(), bool_implies(), bool_not(), bool_or(), YYSTYPE::boolo, YYSTYPE::boolt, catalog_corpus(), CD, TCorpus::charset, YYSTYPE::cl, cl_free, cl_malloc(), cl_randomize(), cl_set_seed(), cl_strdup(), cmp_eq, cmp_get, cmp_gt, cmp_let, cmp_lt, cmp_neq, cnode, CompCorpus, CompCorpusFreqs, CompDirectory, CompLexicon, CompLexiconIdx, CompLexiconSrt, CompRevCorpus, CompRevCorpusIdx, YYSTYPE::context, cqpmessage(), cregerror, cregerror_cleanup(), cregestring, cregSetAttrComponentPath, CurEnv, current_corpus, declare_default_components(), define_macro(), YYSTYPE::direction, ctxtsp::direction, YYSTYPE::Distance, do_AddSubVariables(), do_AnchorPoint(), do_attribute_show(), do_cat(), do_cut(), do_delete_lines(), do_delete_lines_num(), do_Description(), do_dump(), do_exec(), do_flagged_re_variable(), do_flagged_string(), do_group(), do_group2(), do_IDReference(), do_info(), do_LabelReference(), do_MeetStatement(), do_MUQuery(), do_mval_string(), do_NamedWfPattern(), do_OptDistance(), do_PrintAllVariables(), do_printVariableSize(), do_PrintVariableValue(), do_reduce(), do_RelExExpr(), do_RelExpr(), do_save(), do_SearchPattern(), do_set_complex_target(), do_set_target(), do_setop(), do_SetVariableValue(), do_SimpleVariableReference(), do_size(), do_sleep(), do_StandardQuery(), do_start_timer(), do_StringConstraint(), do_StructuralContext(), do_subset(), do_TABQuery(), do_timing(), do_undump(), do_UnionStatement(), do_WordformPattern(), do_XMLTag(), drop_temp_corpora(), dropcorpus(), enable_macros, Error, YYSTYPE::evalt, exit_cqp, expansion, YYSTYPE::field, field_type_to_name(), find_option(), findcorpus(), FindVariable(), _TabulationItem::flags, float_leaf, free_tabulation_list(), FreeSortClause(), FunctionCall(), generate_code, GlobalPrintMode, TCorpus::groupAccessList, hard_boundary, TCorpus::hostAccessList, TCorpus::id, YYSTYPE::idlist, IGNORE_REGEX, in_CorpusCommand(), YYSTYPE::in_redir, in_UnnamedCorpusCommand(), YYSTYPE::index, TCorpus::info_file, int_leaf, YYSTYPE::ival, KeywordField, LAB_DEFINED, labellookup(), evalenv::labels, last, leaf, left, leftright, list_macros(), load_macro_file(), make_first_tabular_pattern(), makearg(), evalenv::match_label, evalenv::matchend_label, MatchEndField, MatchField, Message, mode, TCorpus::name, evalenv::negated, New, NEW_BNODE, NEW_EVALLEAF, NEW_EVALNODE, new_tabulation_item(), _ActualParamList::next, _idbuf::next, _DynArg::next, TCorpus::next, next_environment(), node, NoField, TCorpus::nr_of_loads, NULL, old_query_corpus, OP_CONTAINS, OP_EQUAL, OP_MATCHES, OP_NOT, TCorpus::path, prepare_AlignmentConstraints(), prepare_do_subset(), prepare_input(), prepare_parse(), prepare_Query(), print_macro_definition(), print_option_value(), print_option_values(), print_tabulation(), PrintContextDescriptor(), TCorpus::properties, query_corpus, query_lock, RangeSetop(), RDiff, re_repeat, YYSTYPE::redir, reg_disj(), reg_seq(), TCorpus::registry_dir, TCorpus::registry_name, repeat_inf, resetQueryBuffer(), right, RIntersection, RMaximalMatches, YYSTYPE::rngsetop, RUnion, evalenv::search_context, SELECTED_LINES, set_context_option_value(), set_integer_option_value(), set_string_option_value(), setup_attribute(), show_corpora_files(), ctxtsp::size, size2, YYSTYPE::sortclause, SortSubcorpus(), SortSubcorpusRandomize(), YYSTYPE::storage, _idbuf::string, YYSTYPE::strval, SUB, synchronize(), SYSTEM, YYSTYPE::tabulation_item, TargetField, ctxtsp::type, UNDEF, UNSELECTED_LINES, TCorpus::userAccessList, var_ref, YYSTYPE::varsetting, YYSTYPE::varval, warn_query_lock_violation(), Warning, within_gc, word, YY_, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, yydestruct(), YYDPRINTF, YYEMPTY, YYEOF, yyerror, YYFINAL, YYID, YYLAST, YYMAXDEPTH, YYPACT_NINF, YYPOPSTACK, YYSIZE_T, yyalloc::yyss_alloc, YYSTACK_ALLOC, YYSTACK_ALLOC_MAXIMUM, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, YYTABLE_NINF, YYTERROR, YYTRANSLATE, and yyalloc::yyvs_alloc.
Variable Documentation
int yychar
const yytype_uint16 yycheck[] [static]
const yytype_uint16 yydefact[] [static]
const yytype_int16 yydefgoto[] [static]
Initial value:
{
      -1,     2,     3,     8,     9,    77,    10,    11,    20,    21,
      22,    23,    51,    12,    52,    53,   173,   174,   363,   364,
      54,   107,   108,    24,    25,    26,   306,    55,    98,    56,
      57,   182,    58,   349,   487,   491,   196,    59,    60,    61,
     412,    62,   217,   218,   298,   299,   300,   368,    63,   203,
     204,   414,   450,   471,    64,   357,    65,   210,    66,    67,
      68,    69,   297,   216,    87,    88,    89,    90,   246,    91,
      92,   260,   402,   163,   164,   165,   166,   266,   167,   168,
     255,   169,   141,   226,   150,   151,   152,   230,   344,   157,
     399,   438,   228,   250,   308,   287,   442,    84,   138,   309,
      80,    81,   237,   238,   256,   257,   239,   388,   330,   240,
     389,   390,   241,   153,   154,   435,   155,    93,   142,   224,
     311,    70,   303,   373,   422,    71,    72,    73,   457,    74,
     115,   212,   415,   177,   347,   370,   301
}
YYSTYPE yylval
int yynerrs
const yytype_int16 yypact[] [static]
const yytype_int16 yypgoto[] [static]
Initial value:
{
    -300,  -300,  -300,  -300,  -300,  -300,  -300,  -300,  -300,   376,
    -300,  -300,  -300,  -300,  -300,  -300,   -96,  -300,  -300,  -300,
    -300,  -300,   350,   433,  -300,  -300,  -300,  -300,  -300,  -300,
    -300,  -300,  -300,  -300,  -300,  -300,  -300,  -300,  -300,  -300,
    -170,  -300,  -300,  -300,     7,    97,  -300,  -300,  -300,   307,
     347,  -300,  -300,  -300,  -300,  -300,  -300,  -300,  -300,  -300,
    -300,  -300,  -300,  -300,  -300,  -300,  -300,  -300,   209,    27,
    -300,  -300,  -300,   308,   207,  -157,  -300,  -300,  -300,  -300,
    -300,   -82,  -300,  -300,   241,  -260,  -300,  -277,  -300,  -300,
    -300,  -300,    66,  -203,     4,  -300,    47,  -300,  -222,   160,
     301,   150,  -143,  -300,   230,  -300,  -299,   144,  -300,  -300,
    -300,    48,   239,  -176,  -300,  -300,  -300,  -300,  -300,  -300,
    -300,  -300,  -300,  -300,  -300,  -300,  -300,  -300,    52,  -300,
    -300,  -300,  -300,   -86,  -268,    26,  -113
}
const yytype_uint16 yyr1[] [static]
const yytype_uint8 yyr2[] [static]
const yytype_uint16 yystos[] [static]
const yytype_int16 yytable[] [static]
const yytype_uint8 yytranslate[] [static]