CWB: mingw-libgnurx-2.5.1/regcomp.c File Reference
regcomp.c File Reference
Defines
#define REG_NOERROR_IDX 0
#define REG_NOMATCH_IDX (REG_NOERROR_IDX + sizeof "Success")
#define REG_BADPAT_IDX (REG_NOMATCH_IDX + sizeof "No match")
#define REG_ECOLLATE_IDX (REG_BADPAT_IDX + sizeof "Invalid regular expression")
#define REG_ECTYPE_IDX (REG_ECOLLATE_IDX + sizeof "Invalid collation character")
#define REG_EESCAPE_IDX (REG_ECTYPE_IDX + sizeof "Invalid character class name")
#define REG_ESUBREG_IDX (REG_EESCAPE_IDX + sizeof "Trailing backslash")
#define REG_EBRACK_IDX (REG_ESUBREG_IDX + sizeof "Invalid back reference")
#define REG_EPAREN_IDX (REG_EBRACK_IDX + sizeof "Unmatched [ or [^")
#define REG_EBRACE_IDX (REG_EPAREN_IDX + sizeof "Unmatched (or \\(")
#define REG_BADBR_IDX (REG_EBRACE_IDX + sizeof "Unmatched \\{")
#define REG_ERANGE_IDX (REG_BADBR_IDX + sizeof "Invalid content of \\{\\}")
#define REG_ESPACE_IDX (REG_ERANGE_IDX + sizeof "Invalid range end")
#define REG_BADRPT_IDX (REG_ESPACE_IDX + sizeof "Memory exhausted")
#define REG_EEND_IDX (REG_BADRPT_IDX + sizeof "Invalid preceding regular expression")
#define REG_ESIZE_IDX (REG_EEND_IDX + sizeof "Premature end of regular expression")
#define REG_ERPAREN_IDX (REG_ESIZE_IDX + sizeof "Regular expression too big")
#define BRACKET_NAME_BUF_SIZE 32
#define BUILD_CHARCLASS_LOOP(ctype_func)
Functions
static reg_errcode_t re_compile_internal (regex_t *preg, const char *pattern, size_t length, reg_syntax_t syntax)
static void re_compile_fastmap_iter (regex_t *bufp, const re_dfastate_t *init_state, char *fastmap)
static reg_errcode_t init_dfa (re_dfa_t *dfa, size_t pat_len)
static void free_workarea_compile (regex_t *preg)
static reg_errcode_t create_initial_state (re_dfa_t *dfa)
static reg_errcode_t analyze (regex_t *preg)
static reg_errcode_t preorder (bin_tree_t *root, reg_errcode_t(fn(void *, bin_tree_t *)), void *extra)
static reg_errcode_t postorder (bin_tree_t *root, reg_errcode_t(fn(void *, bin_tree_t *)), void *extra)
static reg_errcode_t optimize_subexps (void *extra, bin_tree_t *node)
static reg_errcode_t lower_subexps (void *extra, bin_tree_t *node)
static bin_tree_t * lower_subexp (reg_errcode_t *err, regex_t *preg, bin_tree_t *node)
static reg_errcode_t calc_first (void *extra, bin_tree_t *node)
static reg_errcode_t calc_next (void *extra, bin_tree_t *node)
static reg_errcode_t link_nfa_nodes (void *extra, bin_tree_t *node)
static int duplicate_node (re_dfa_t *dfa, int org_idx, unsigned int constraint)
static int search_duplicated_node (const re_dfa_t *dfa, int org_node, unsigned int constraint)
static reg_errcode_t calc_eclosure (re_dfa_t *dfa)
static reg_errcode_t calc_eclosure_iter (re_node_set *new_set, re_dfa_t *dfa, int node, int root)
static reg_errcode_t calc_inveclosure (re_dfa_t *dfa)
static int fetch_number (re_string_t *input, re_token_t *token, reg_syntax_t syntax)
static int peek_token (re_token_t *token, re_string_t *input, reg_syntax_t syntax) internal_function
static bin_tree_t * parse (re_string_t *regexp, regex_t *preg, reg_syntax_t syntax, reg_errcode_t *err)
static bin_tree_t * parse_reg_exp (re_string_t *regexp, regex_t *preg, re_token_t *token, reg_syntax_t syntax, int nest, reg_errcode_t *err)
static bin_tree_t * parse_branch (re_string_t *regexp, regex_t *preg, re_token_t *token, reg_syntax_t syntax, int nest, reg_errcode_t *err)
static bin_tree_t * parse_expression (re_string_t *regexp, regex_t *preg, re_token_t *token, reg_syntax_t syntax, int nest, reg_errcode_t *err)
static bin_tree_t * parse_sub_exp (re_string_t *regexp, regex_t *preg, re_token_t *token, reg_syntax_t syntax, int nest, reg_errcode_t *err)
static bin_tree_t * parse_dup_op (bin_tree_t *dup_elem, re_string_t *regexp, re_dfa_t *dfa, re_token_t *token, reg_syntax_t syntax, reg_errcode_t *err)
static bin_tree_t * parse_bracket_exp (re_string_t *regexp, re_dfa_t *dfa, re_token_t *token, reg_syntax_t syntax, reg_errcode_t *err)
static reg_errcode_t parse_bracket_element (bracket_elem_t *elem, re_string_t *regexp, re_token_t *token, int token_len, re_dfa_t *dfa, reg_syntax_t syntax, int accept_hyphen)
static reg_errcode_t parse_bracket_symbol (bracket_elem_t *elem, re_string_t *regexp, re_token_t *token)
static reg_errcode_t build_equiv_class (bitset_t sbcset, const unsigned char *name)
static reg_errcode_t build_charclass (RE_TRANSLATE_TYPE trans, bitset_t sbcset, const unsigned char *class_name, reg_syntax_t syntax)
static bin_tree_t * build_charclass_op (re_dfa_t *dfa, RE_TRANSLATE_TYPE trans, const unsigned char *class_name, const unsigned char *extra, int non_match, reg_errcode_t *err)
static bin_tree_t * create_tree (re_dfa_t *dfa, bin_tree_t *left, bin_tree_t *right, re_token_type_t type)
static bin_tree_t * create_token_tree (re_dfa_t *dfa, bin_tree_t *left, bin_tree_t *right, const re_token_t *token)
static bin_tree_t * duplicate_tree (const bin_tree_t *src, re_dfa_t *dfa)
static void free_token (re_token_t *node)
static reg_errcode_t free_tree (void *extra, bin_tree_t *node)
static reg_errcode_t mark_opt_subexp (void *extra, bin_tree_t *node)
const char * re_compile_pattern (char *pattern, size_t length, struct re_pattern_buffer *bufp) const
reg_syntax_t re_set_syntax (reg_syntax_t syntax)
int re_compile_fastmap (struct re_pattern_buffer *bufp)
static void __attribute ((always_inline))
int regcomp (regex_t *__restrict preg, const char *__restrict pattern, int cflags)
size_t regerror (int errcode, const regex_t *__restrict preg, char *__restrict errbuf, size_t errbuf_size)
static void free_dfa_content (re_dfa_t *dfa)
void regfree (regex_t *preg)
static void internal_function init_word_char (re_dfa_t *dfa)
static reg_errcode_t
internal_function duplicate_node_closure (re_dfa_t *dfa, int top_org_node, int top_clone_node, int root_node, unsigned int init_constraint)
static void internal_function fetch_token (re_token_t *result, re_string_t *input, reg_syntax_t syntax)
static int internal_function peek_token_bracket (re_token_t *token, re_string_t *input, reg_syntax_t syntax)
static reg_errcode_t
internal_function build_range_exp (bitset_t sbcset, bracket_elem_t *start_elem, bracket_elem_t *end_elem)
static reg_errcode_t
internal_function build_collating_symbol (bitset_t sbcset, const unsigned char *name)
Variables
const char __re_error_msgid[] attribute_hidden
reg_syntax_t re_syntax_options
Define Documentation
#define BRACKET_NAME_BUF_SIZE 32
Referenced by parse_bracket_exp(), and parse_bracket_symbol().
#define BUILD_CHARCLASS_LOOP (ctype_func)
Value:
do {            \
    if (BE (trans != NULL, 0))      \
      {           \
  for (i = 0; i < SBC_MAX; ++i)   \
      if (ctype_func (i))     \
      bitset_set (sbcset, trans[i]);  \
      }           \
    else          \
      {           \
  for (i = 0; i < SBC_MAX; ++i)   \
      if (ctype_func (i))     \
      bitset_set (sbcset, i);   \
      }           \
  } while (0)
Referenced by build_charclass().
#define REG_BADBR_IDX (REG_EBRACE_IDX + sizeof "Unmatched \\{")
#define REG_BADPAT_IDX (REG_NOMATCH_IDX + sizeof "No match")
#define REG_BADRPT_IDX (REG_ESPACE_IDX + sizeof "Memory exhausted")
#define REG_EBRACE_IDX (REG_EPAREN_IDX + sizeof "Unmatched (or \\(")
#define REG_EBRACK_IDX (REG_ESUBREG_IDX + sizeof "Invalid back reference")
#define REG_ECOLLATE_IDX (REG_BADPAT_IDX + sizeof "Invalid regular expression")
#define REG_ECTYPE_IDX (REG_ECOLLATE_IDX + sizeof "Invalid collation character")
#define REG_EEND_IDX (REG_BADRPT_IDX + sizeof "Invalid preceding regular expression")
#define REG_EESCAPE_IDX (REG_ECTYPE_IDX + sizeof "Invalid character class name")
#define REG_EPAREN_IDX (REG_EBRACK_IDX + sizeof "Unmatched [ or [^")
#define REG_ERANGE_IDX (REG_BADBR_IDX + sizeof "Invalid content of \\{\\}")
#define REG_ERPAREN_IDX (REG_ESIZE_IDX + sizeof "Regular expression too big")
#define REG_ESIZE_IDX (REG_EEND_IDX + sizeof "Premature end of regular expression")
#define REG_ESPACE_IDX (REG_ERANGE_IDX + sizeof "Invalid range end")
#define REG_ESUBREG_IDX (REG_EESCAPE_IDX + sizeof "Trailing backslash")
#define REG_NOERROR_IDX 0
#define REG_NOMATCH_IDX (REG_NOERROR_IDX + sizeof "Success")
Function Documentation
static void __attribute ((always_inline)) [inline, static]
static reg_errcode_t analyze (regex_t * preg) [static]
References BE, re_pattern_buffer::buffer, calc_eclosure(), calc_first(), calc_inveclosure(), calc_next(), re_dfa_t::eclosures, re_dfa_t::edests, re_dfa_t::has_plural_match, re_dfa_t::inveclosures, link_nfa_nodes(), lower_subexps(), re_dfa_t::nbackref, re_dfa_t::nexts, re_pattern_buffer::no_sub, re_dfa_t::nodes_alloc, re_dfa_t::nodes_len, optimize_subexps(), re_dfa_t::org_indices, postorder(), preorder(), re_malloc, re_pattern_buffer::re_nsub, REG_ESPACE, REG_NOERROR, re_dfa_t::str_tree, and re_dfa_t::subexp_map.
Referenced by re_compile_internal().
static reg_errcode_t build_charclass (RE_TRANSLATE_TYPE trans, bitset_t sbcset, const unsigned char * class_name, reg_syntax_t syntax) [static]
References __wctype, BE, BUILD_CHARCLASS_LOOP, isblank, RE_ICASE, re_realloc, REG_ECTYPE, REG_ESPACE, and REG_NOERROR.
Referenced by build_charclass_op(), and parse_bracket_exp().
static bin_tree_t * build_charclass_op (re_dfa_t * dfa, RE_TRANSLATE_TYPE trans, const unsigned char * class_name, const unsigned char * extra, int non_match, reg_errcode_t * err) [static]
References BE, bitset_mask(), bitset_not(), bitset_set, build_charclass(), create_token_tree(), create_tree(), re_dfa_t::has_mb_node, re_dfa_t::mb_cur_max, re_token_t::opr, re_free, REG_ESPACE, REG_NOERROR, re_dfa_t::sb_char, re_token_t::sbcset, SIMPLE_BRACKET, and re_token_t::type.
Referenced by parse_expression().
static reg_errcode_t internal_function build_collating_symbol (bitset_t sbcset, const unsigned char * name) [static]
References BE, bitset_set, REG_ECOLLATE, and REG_NOERROR.
Referenced by parse_bracket_exp().
static reg_errcode_t build_equiv_class (bitset_t sbcset, const unsigned char * name) [static]
References BE, bitset_set, re_realloc, REG_ECOLLATE, REG_ESPACE, REG_NOERROR, and SBC_MAX.
Referenced by parse_bracket_exp().
static reg_errcode_t internal_function build_range_exp (bitset_t sbcset, bracket_elem_t * start_elem, bracket_elem_t * end_elem) [static]
References __btowc, BE, bitset_set, bracket_elem_t::ch, CHAR_CLASS, COLL_SYM, EQUIV_CLASS, bracket_elem_t::name, bracket_elem_t::opr, re_realloc, REG_ECOLLATE, REG_ERANGE, REG_ESPACE, REG_NOERROR, SB_CHAR, SBC_MAX, bracket_elem_t::type, and bracket_elem_t::wch.
Referenced by parse_bracket_exp().
static reg_errcode_t calc_eclosure (re_dfa_t * dfa) [static]
References BE, calc_eclosure_iter(), re_dfa_t::eclosures, re_node_set::nelem, re_dfa_t::nodes_len, re_node_set_free, and REG_NOERROR.
Referenced by analyze().
static reg_errcode_t calc_eclosure_iter (re_node_set * new_set, re_dfa_t * dfa, int node, int root) [static]
References BE, re_token_t::ctx_type, duplicate_node_closure(), re_token_t::duplicated, re_dfa_t::eclosures, re_dfa_t::edests, re_node_set::elems, IS_EPSILON_NODE, re_node_set::nelem, re_dfa_t::nodes, re_token_t::opr, re_node_set_alloc(), re_node_set_free, re_node_set_insert(), re_node_set_merge(), REG_NOERROR, and re_token_t::type.
Referenced by calc_eclosure().
static reg_errcode_t calc_first (void * extra, bin_tree_t * node) [static]
References BE, bin_tree_t::first, bin_tree_t::left, bin_tree_t::node_idx, re_dfa_add_node(), REG_ESPACE, REG_NOERROR, bin_tree_t::token, and re_token_t::type.
Referenced by analyze().
static reg_errcode_t calc_inveclosure (re_dfa_t * dfa) [static]
References BE, re_dfa_t::eclosures, re_node_set::elems, re_dfa_t::inveclosures, re_node_set::nelem, re_dfa_t::nodes_len, re_node_set_init_empty, re_node_set_insert_last(), REG_ESPACE, and REG_NOERROR.
Referenced by analyze().
static reg_errcode_t calc_next (void * extra, bin_tree_t * node) [static]
References bin_tree_t::first, bin_tree_t::left, bin_tree_t::next, REG_NOERROR, bin_tree_t::right, bin_tree_t::token, and re_token_t::type.
Referenced by analyze().
static reg_errcode_t create_initial_state (re_dfa_t * dfa) [static]
References BE, CONTEXT_BEGBUF, CONTEXT_NEWLINE, CONTEXT_WORD, re_dfa_t::eclosures, re_dfa_t::edests, re_node_set::elems, bin_tree_t::first, re_dfastate_t::has_constraint, re_token_t::idx, re_dfa_t::init_node, re_dfa_t::init_state, re_dfa_t::init_state_begbuf, re_dfa_t::init_state_nl, re_dfa_t::init_state_word, re_dfa_t::nbackref, re_node_set::nelem, bin_tree_t::node_idx, re_dfa_t::nodes, OP_BACK_REF, re_token_t::opr, re_acquire_state_context(), re_node_set_free, re_node_set_init_copy(), re_node_set_merge(), REG_NOERROR, re_dfa_t::str_tree, and re_token_t::type.
Referenced by re_compile_internal().
static bin_tree_t * create_token_tree (re_dfa_t * dfa, bin_tree_t * left, bin_tree_t * right, const re_token_t * token) [static]
References BE, BIN_TREE_STORAGE_SIZE, bin_tree_storage_t::data, re_token_t::duplicated, bin_tree_t::first, bin_tree_t::left, bin_tree_t::next, bin_tree_storage_t::next, bin_tree_t::node_idx, re_token_t::opt_subexp, bin_tree_t::parent, re_malloc, bin_tree_t::right, re_dfa_t::str_tree_storage, re_dfa_t::str_tree_storage_idx, and bin_tree_t::token.
Referenced by build_charclass_op(), create_tree(), duplicate_tree(), parse_bracket_exp(), and parse_expression().
static bin_tree_t * create_tree (re_dfa_t * dfa, bin_tree_t * left, bin_tree_t * right, re_token_type_t type) [static]
References create_token_tree(), and re_token_t::type.
Referenced by build_charclass_op(), lower_subexp(), parse(), parse_bracket_exp(), parse_branch(), parse_dup_op(), parse_expression(), parse_reg_exp(), and parse_sub_exp().
static int duplicate_node (re_dfa_t * dfa, int org_idx, unsigned int constraint) [static]
References BE, re_token_t::constraint, re_token_t::ctx_type, re_token_t::duplicated, re_dfa_t::nodes, re_token_t::opr, re_dfa_t::org_indices, re_dfa_add_node(), and re_token_t::type.
Referenced by duplicate_node_closure().
static reg_errcode_t internal_function duplicate_node_closure (re_dfa_t * dfa, int top_org_node, int top_clone_node, int root_node, unsigned int init_constraint) [static]
References BE, re_token_t::ctx_type, duplicate_node(), re_dfa_t::edests, re_node_set::elems, re_node_set::nelem, re_dfa_t::nexts, re_dfa_t::nodes, OP_BACK_REF, re_token_t::opr, re_node_set_empty, re_node_set_insert(), REG_ESPACE, REG_NOERROR, search_duplicated_node(), and re_token_t::type.
Referenced by calc_eclosure_iter().
static bin_tree_t * duplicate_tree (const bin_tree_t * src, re_dfa_t * dfa) [static]
References create_token_tree(), bin_tree_t::left, bin_tree_t::parent, bin_tree_t::right, and bin_tree_t::token.
Referenced by parse_dup_op().
static int fetch_number (re_string_t * input, re_token_t * token, reg_syntax_t syntax) [static]
References BE, re_token_t::c, CHARACTER, END_OF_RE, fetch_token(), re_token_t::opr, RE_DUP_MAX, and re_token_t::type.
Referenced by parse_dup_op().
static void internal_function fetch_token (re_token_t * result, re_string_t * input, reg_syntax_t syntax) [static]
References peek_token(), and re_string_skip_bytes.
Referenced by fetch_number(), parse(), parse_dup_op(), parse_expression(), parse_reg_exp(), and parse_sub_exp().
static void free_dfa_content (re_dfa_t * dfa) [static]
References re_state_table_entry::array, re_dfa_t::eclosures, re_dfa_t::edests, free_state(), free_token(), re_dfa_t::inveclosures, re_dfa_t::nexts, re_dfa_t::nodes, re_dfa_t::nodes_len, re_state_table_entry::num, re_free, re_node_set_free, re_dfa_t::sb_char, re_dfa_t::state_hash_mask, re_dfa_t::state_table, and re_dfa_t::subexp_map.
Referenced by re_compile_internal(), and regfree().
static void free_token (re_token_t * node) [static]
References re_token_t::duplicated, re_token_t::opr, re_free, re_token_t::sbcset, SIMPLE_BRACKET, and re_token_t::type.
Referenced by free_dfa_content(), and free_tree().
static reg_errcode_t free_tree (void * extra, bin_tree_t * node) [static]
References free_token(), REG_NOERROR, and bin_tree_t::token.
Referenced by parse_dup_op().
static void free_workarea_compile (regex_t * preg) [static]
References BIN_TREE_STORAGE_SIZE, re_pattern_buffer::buffer, bin_tree_storage_t::next, re_dfa_t::org_indices, re_free, re_dfa_t::str_tree, re_dfa_t::str_tree_storage, and re_dfa_t::str_tree_storage_idx.
Referenced by re_compile_internal().
static reg_errcode_t init_dfa (re_dfa_t * dfa, size_t pat_len) [static]
References __btowc, BE, BIN_TREE_STORAGE_SIZE, BITSET_WORD_BITS, BITSET_WORDS, re_dfa_t::is_utf8, re_dfa_t::map_notascii, re_dfa_t::mb_cur_max, re_dfa_t::nodes, re_dfa_t::nodes_alloc, re_malloc, REG_ESPACE, REG_NOERROR, re_dfa_t::sb_char, SIZE_MAX, re_dfa_t::state_hash_mask, re_dfa_t::state_table, re_dfa_t::str_tree_storage_idx, and table_size().
static void internal_function init_word_char (re_dfa_t * dfa) [static]
References BITSET_WORD_BITS, BITSET_WORDS, re_dfa_t::word_char, and re_dfa_t::word_ops_used.
Referenced by parse_expression().
static reg_errcode_t link_nfa_nodes (void * extra, bin_tree_t * node) [static]
References re_dfa_t::edests, END_OF_RE, bin_tree_t::first, re_dfa_t::has_plural_match, IS_EPSILON_NODE, bin_tree_t::left, left, bin_tree_t::next, re_dfa_t::nexts, bin_tree_t::node_idx, OP_BACK_REF, re_node_set_init_1(), re_node_set_init_2(), REG_NOERROR, bin_tree_t::right, right, bin_tree_t::token, and re_token_t::type.
Referenced by analyze().
static bin_tree_t * lower_subexp (reg_errcode_t * err, regex_t * preg, bin_tree_t * node) [static]
References BE, BITSET_WORD_BITS, re_pattern_buffer::buffer, create_tree(), re_token_t::idx, bin_tree_t::left, re_pattern_buffer::no_sub, re_token_t::opr, re_token_t::opt_subexp, REG_ESPACE, bin_tree_t::token, and re_dfa_t::used_bkref_map.
Referenced by lower_subexps().
static reg_errcode_t lower_subexps (void * extra, bin_tree_t * node) [static]
References bin_tree_t::left, lower_subexp(), bin_tree_t::parent, REG_NOERROR, bin_tree_t::right, bin_tree_t::token, and re_token_t::type.
Referenced by analyze().
static reg_errcode_t mark_opt_subexp (void * extra, bin_tree_t * node) [static]
References re_token_t::idx, re_token_t::opr, re_token_t::opt_subexp, REG_NOERROR, bin_tree_t::token, and re_token_t::type.
Referenced by parse_dup_op().
static reg_errcode_t optimize_subexps (void * extra, bin_tree_t * node) [static]
References BITSET_WORD_BITS, re_token_t::idx, bin_tree_t::left, OP_BACK_REF, re_token_t::opr, bin_tree_t::parent, REG_NOERROR, re_dfa_t::subexp_map, bin_tree_t::token, re_token_t::type, and re_dfa_t::used_bkref_map.
Referenced by analyze().
static bin_tree_t * parse (re_string_t * regexp, regex_t * preg, reg_syntax_t syntax, reg_errcode_t * err) [static]
References BE, re_pattern_buffer::buffer, create_tree(), END_OF_RE, fetch_token(), parse_reg_exp(), RE_CARET_ANCHORS_HERE, REG_ESPACE, REG_NOERROR, and re_dfa_t::syntax.
Referenced by re_compile_internal().
static reg_errcode_t parse_bracket_element (bracket_elem_t * elem, re_string_t * regexp, re_token_t * token, int token_len, re_dfa_t * dfa, reg_syntax_t syntax, int accept_hyphen) [static]
References BE, re_token_t::c, bracket_elem_t::ch, MB_CHAR, re_token_t::opr, bracket_elem_t::opr, parse_bracket_symbol(), peek_token_bracket(), re_string_cur_idx, re_string_skip_bytes, REG_ERANGE, REG_NOERROR, SB_CHAR, re_token_t::type, bracket_elem_t::type, and bracket_elem_t::wch.
Referenced by parse_bracket_exp().
static bin_tree_t * parse_bracket_exp (re_string_t * regexp, re_dfa_t * dfa, re_token_t * token, reg_syntax_t syntax, reg_errcode_t * err) [static]
References __attribute, __btowc, BE, bitset_mask(), bitset_not(), bitset_set, BRACKET_NAME_BUF_SIZE, build_charclass(), build_collating_symbol(), build_equiv_class(), build_range_exp(), bracket_elem_t::ch, CHAR_CLASS, CHARACTER, COLL_SYM, create_token_tree(), create_tree(), END_OF_RE, EQUIV_CLASS, re_dfa_t::has_mb_node, MB_CHAR, re_dfa_t::mb_cur_max, bracket_elem_t::name, re_token_t::opr, bracket_elem_t::opr, parse_bracket_element(), peek_token_bracket(), re_free, RE_HAT_LISTS_NOT_NEWLINE, RE_NO_EMPTY_RANGES, re_realloc, re_string_skip_bytes, REG_BADPAT, REG_EBRACK, REG_ECOLLATE, REG_ERANGE, REG_ESPACE, REG_NOERROR, re_dfa_t::sb_char, SB_CHAR, SBC_MAX, re_token_t::sbcset, SIMPLE_BRACKET, table_size(), re_string_t::trans, re_token_t::type, bracket_elem_t::type, and bracket_elem_t::wch.
Referenced by parse_expression().
static reg_errcode_t parse_bracket_symbol (bracket_elem_t * elem, re_string_t * regexp, re_token_t * token) [static]
References BRACKET_NAME_BUF_SIZE, re_token_t::c, CHAR_CLASS, COLL_SYM, EQUIV_CLASS, bracket_elem_t::name, bracket_elem_t::opr, re_token_t::opr, re_string_eoi, re_string_fetch_byte, re_string_peek_byte, re_string_skip_bytes, REG_EBRACK, REG_NOERROR, bracket_elem_t::type, and re_token_t::type.
Referenced by parse_bracket_element().
static bin_tree_t * parse_branch (re_string_t * regexp, regex_t * preg, re_token_t * token, reg_syntax_t syntax, int nest, reg_errcode_t * err) [static]
References BE, re_pattern_buffer::buffer, create_tree(), END_OF_RE, parse_expression(), REG_ESPACE, REG_NOERROR, and re_token_t::type.
Referenced by parse_reg_exp().
static bin_tree_t * parse_dup_op (bin_tree_t * dup_elem, re_string_t * regexp, re_dfa_t * dfa, re_token_t * token, reg_syntax_t syntax, reg_errcode_t * err) [static]
References BE, re_token_t::c, CHARACTER, create_tree(), duplicate_tree(), END_OF_RE, fetch_number(), fetch_token(), free_tree(), re_token_t::idx, mark_opt_subexp(), re_token_t::opr, postorder(), RE_INVALID_INTERVAL_ORD, re_string_cur_idx, re_string_set_index, REG_BADBR, REG_EBRACE, REG_ESPACE, bin_tree_t::token, and re_token_t::type.
Referenced by parse_expression().
static bin_tree_t * parse_expression (re_string_t * regexp, regex_t * preg, re_token_t * token, reg_syntax_t syntax, int nest, reg_errcode_t * err) [static]
References BE, re_pattern_buffer::buffer, build_charclass_op(), CHARACTER, re_dfa_t::completed_bkref_map, create_token_tree(), create_tree(), re_token_t::ctx_type, END_OF_RE, fetch_token(), re_dfa_t::has_mb_node, re_token_t::idx, init_word_char(), INSIDE_NOTWORD, INSIDE_WORD, re_dfa_t::mb_cur_max, re_dfa_t::nbackref, NOT_WORD_DELIM, OP_BACK_REF, OP_PERIOD, re_token_t::opr, parse_bracket_exp(), parse_dup_op(), parse_sub_exp(), RE_CONTEXT_INDEP_OPS, RE_CONTEXT_INVALID_DUP, RE_CONTEXT_INVALID_OPS, re_string_cur_idx, re_string_eoi, re_string_first_byte, RE_UNMATCHED_RIGHT_PAREN_ORD, REG_BADRPT, REG_EESCAPE, REG_ERPAREN, REG_ESPACE, REG_ESUBREG, REG_NOERROR, re_string_t::trans, re_token_t::type, re_dfa_t::used_bkref_map, WORD_DELIM, WORD_FIRST, WORD_LAST, and re_dfa_t::word_ops_used.
Referenced by parse_branch().
static bin_tree_t * parse_reg_exp (re_string_t * regexp, regex_t * preg, re_token_t * token, reg_syntax_t syntax, int nest, reg_errcode_t * err) [static]
References BE, re_pattern_buffer::buffer, create_tree(), END_OF_RE, fetch_token(), parse_branch(), RE_CARET_ANCHORS_HERE, REG_ESPACE, REG_NOERROR, and re_token_t::type.
Referenced by parse(), and parse_sub_exp().
static bin_tree_t * parse_sub_exp (re_string_t * regexp, regex_t * preg, re_token_t * token, reg_syntax_t syntax, int nest, reg_errcode_t * err) [static]
References BE, re_pattern_buffer::buffer, re_dfa_t::completed_bkref_map, create_tree(), fetch_token(), parse_reg_exp(), RE_CARET_ANCHORS_HERE, re_pattern_buffer::re_nsub, REG_EPAREN, REG_ESPACE, REG_NOERROR, and re_token_t::type.
Referenced by parse_expression().
static int internal_function peek_token (re_token_t * token, re_string_t * input, reg_syntax_t syntax) [static]
References BUF_FIRST, BUF_LAST, re_token_t::c, CHARACTER, re_token_t::ctx_type, END_OF_RE, re_token_t::idx, IS_WIDE_WORD_CHAR, IS_WORD_CHAR, LINE_FIRST, LINE_LAST, re_string_t::mb_cur_max, NOT_WORD_DELIM, OP_BACK_REF, OP_PERIOD, re_token_t::opr, RE_BK_PLUS_QM, RE_CARET_ANCHORS_HERE, RE_CONTEXT_INDEP_ANCHORS, RE_INTERVALS, RE_LIMITED_OPS, RE_NEWLINE_ALT, RE_NO_BK_BRACES, RE_NO_BK_PARENS, RE_NO_BK_REFS, RE_NO_BK_VBAR, RE_NO_GNU_OPS, re_string_cur_idx, re_string_eoi, re_string_first_byte, re_string_length, re_string_peek_byte, re_string_skip_bytes, re_token_t::type, re_token_t::word_char, WORD_DELIM, WORD_FIRST, and WORD_LAST.
Referenced by fetch_token().
static int internal_function peek_token_bracket (re_token_t * token, re_string_t * input, reg_syntax_t syntax) [static]
References re_token_t::c, CHARACTER, END_OF_RE, re_string_t::mb_cur_max, re_token_t::opr, RE_BACKSLASH_ESCAPE_IN_LISTS, RE_CHAR_CLASSES, re_string_cur_idx, re_string_eoi, re_string_first_byte, re_string_length, re_string_peek_byte, re_string_skip_bytes, and re_token_t::type.
Referenced by parse_bracket_element(), and parse_bracket_exp().
static reg_errcode_t postorder (bin_tree_t * root, reg_errcode_t(fn(void *, bin_tree_t *)) , void * extra) [static]
References BE, bin_tree_t::left, bin_tree_t::parent, REG_NOERROR, and bin_tree_t::right.
Referenced by analyze(), and parse_dup_op().
static reg_errcode_t preorder (bin_tree_t * root, reg_errcode_t(fn(void *, bin_tree_t *)) , void * extra) [static]
References BE, bin_tree_t::left, bin_tree_t::parent, REG_NOERROR, and bin_tree_t::right.
Referenced by analyze().
int re_compile_fastmap (struct re_pattern_buffer * bufp)
References re_dfa_t::init_state, re_dfa_t::init_state_begbuf, re_dfa_t::init_state_nl, re_dfa_t::init_state_word, re_compile_fastmap_iter(), and SBC_MAX.
Referenced by re_search_stub(), and regcomp().
static void re_compile_fastmap_iter (regex_t * bufp, const re_dfastate_t * init_state, char * fastmap) [static]
References __btowc, __wcrtomb, BITSET_WORD_BITS, BITSET_WORDS, buf, re_pattern_buffer::buffer, re_token_t::c, re_pattern_buffer::can_be_null, CHARACTER, re_node_set::elems, END_OF_RE, re_dfa_t::mb_cur_max, re_node_set::nelem, node, re_dfa_t::nodes, re_dfastate_t::nodes, OP_PERIOD, re_token_t::opr, RE_ICASE, SBC_MAX, re_token_t::sbcset, SIMPLE_BRACKET, re_pattern_buffer::syntax, and re_token_t::type.
Referenced by re_compile_fastmap().
static reg_errcode_t re_compile_internal (regex_t * preg, const char * pattern, size_t length, reg_syntax_t syntax) [static]
References __libc_lock_init, re_pattern_buffer::allocated, analyze(), BE, re_pattern_buffer::buffer, re_pattern_buffer::can_be_null, create_initial_state(), re_pattern_buffer::fastmap_accurate, free_dfa_content(), free_workarea_compile(), init_dfa(), re_dfa_t::is_utf8, re_pattern_buffer::not_bol, re_pattern_buffer::not_eol, parse(), RE_ICASE, re_malloc, re_pattern_buffer::re_nsub, re_realloc, re_string_construct(), re_string_destruct(), REG_ESPACE, REG_NOERROR, re_pattern_buffer::regs_allocated, REGS_UNALLOCATED, re_dfa_t::str_tree, re_pattern_buffer::syntax, re_pattern_buffer::translate, and re_pattern_buffer::used.
Referenced by re_compile_pattern(), and regcomp().
const char* re_compile_pattern (char * pattern, size_t length, struct re_pattern_buffer * bufp) const
References gettext, re_pattern_buffer::newline_anchor, re_pattern_buffer::no_sub, re_compile_internal(), RE_NO_SUB, and re_syntax_options.
reg_syntax_t re_set_syntax (reg_syntax_t syntax)
int regcomp (regex_t *__restrict preg, const char *__restrict pattern, int cflags)
References BE, re_compile_fastmap(), re_compile_internal(), RE_DOT_NEWLINE, re_free, RE_HAT_LISTS_NOT_NEWLINE, RE_ICASE, re_malloc, RE_SYNTAX_POSIX_BASIC, RE_SYNTAX_POSIX_EXTENDED, REG_EPAREN, REG_ERPAREN, REG_ESPACE, REG_EXTENDED, REG_ICASE, REG_NEWLINE, REG_NOERROR, REG_NOSUB, and SBC_MAX.
size_t regerror (int errcode, const regex_t *__restrict preg, char *__restrict errbuf, size_t errbuf_size)
References __mempcpy, BE, and gettext.
void regfree (regex_t * preg)
References BE, free_dfa_content(), and re_free.
static int search_duplicated_node (const re_dfa_t * dfa, int org_node, unsigned int constraint) [static]
References re_token_t::constraint, re_token_t::duplicated, re_dfa_t::nodes, re_dfa_t::nodes_len, and re_dfa_t::org_indices.
Referenced by duplicate_node_closure().
Variable Documentation
const size_t __re_error_msgid_idx [] attribute_hidden
reg_syntax_t re_syntax_options
Referenced by re_compile_pattern().