CWB: mingw-libgnurx-2.5.1/regex_internal.c File Reference
regex_internal.c File Reference
Functions
static void re_string_construct_common (const char *str, int len, re_string_t *pstr, RE_TRANSLATE_TYPE trans, int icase, const re_dfa_t *dfa) internal_function
static re_dfastate_t * create_ci_newstate (const re_dfa_t *dfa, const re_node_set *nodes, unsigned int hash) internal_function
static re_dfastate_t * create_cd_newstate (const re_dfa_t *dfa, const re_node_set *nodes, unsigned int context, unsigned int hash) internal_function
static reg_errcode_t
internal_function re_string_allocate (re_string_t *pstr, const char *str, int len, int init_len, RE_TRANSLATE_TYPE trans, int icase, const re_dfa_t *dfa)
static reg_errcode_t
internal_function re_string_construct (re_string_t *pstr, const char *str, int len, RE_TRANSLATE_TYPE trans, int icase, const re_dfa_t *dfa)
static reg_errcode_t
internal_function re_string_realloc_buffers (re_string_t *pstr, int new_buf_len)
static void internal_function build_upper_buffer (re_string_t *pstr)
static void internal_function re_string_translate_buffer (re_string_t *pstr)
static reg_errcode_t
internal_function re_string_reconstruct (re_string_t *pstr, int idx, int eflags)
static unsigned char
internal_function __attribute ((pure))
static void internal_function re_string_destruct (re_string_t *pstr)
static unsigned int
internal_function re_string_context_at (const re_string_t *input, int idx, int eflags)
static reg_errcode_t
internal_function re_node_set_alloc (re_node_set *set, int size)
static reg_errcode_t
internal_function re_node_set_init_1 (re_node_set *set, int elem)
static reg_errcode_t
internal_function re_node_set_init_2 (re_node_set *set, int elem1, int elem2)
static reg_errcode_t
internal_function re_node_set_init_copy (re_node_set *dest, const re_node_set *src)
static reg_errcode_t
internal_function re_node_set_add_intersect (re_node_set *dest, const re_node_set *src1, const re_node_set *src2)
static reg_errcode_t
internal_function re_node_set_init_union (re_node_set *dest, const re_node_set *src1, const re_node_set *src2)
static reg_errcode_t
internal_function re_node_set_merge (re_node_set *dest, const re_node_set *src)
static int internal_function re_node_set_insert (re_node_set *set, int elem)
static int internal_function re_node_set_insert_last (re_node_set *set, int elem)
static void internal_function re_node_set_remove_at (re_node_set *set, int idx)
static int internal_function re_dfa_add_node (re_dfa_t *dfa, re_token_t token)
static unsigned int
internal_function calc_state_hash (const re_node_set *nodes, unsigned int context)
static re_dfastate_t
*internal_function re_acquire_state (reg_errcode_t *err, const re_dfa_t *dfa, const re_node_set *nodes)
static re_dfastate_t
*internal_function re_acquire_state_context (reg_errcode_t *err, const re_dfa_t *dfa, const re_node_set *nodes, unsigned int context)
static reg_errcode_t register_state (const re_dfa_t *dfa, re_dfastate_t *newstate, unsigned int hash)
static void free_state (re_dfastate_t *state)
Function Documentation
static int internal_function __attribute ((pure)) [static]
References right.
static void internal_function build_upper_buffer (re_string_t * pstr) [static]
References BE, re_string_t::bufs_len, re_string_t::len, re_string_t::mbs, re_string_t::raw_mbs, re_string_t::raw_mbs_idx, re_string_t::trans, re_string_t::valid_len, and re_string_t::valid_raw_len.
Referenced by extend_buffers(), re_string_construct(), and re_string_reconstruct().
static unsigned int internal_function calc_state_hash (const re_node_set * nodes, unsigned int context) [inline, static]
References re_node_set::elems, and re_node_set::nelem.
Referenced by re_acquire_state(), and re_acquire_state_context().
static re_dfastate_t *internal_function create_cd_newstate (const re_dfa_t * dfa, const re_node_set * nodes, unsigned int context, unsigned int hash) [static]
References re_dfastate_t::accept_mb, BE, CHARACTER, re_token_t::constraint, re_dfastate_t::context, re_token_t::ctx_type, re_node_set::elems, END_OF_RE, re_dfastate_t::entrance_nodes, free_state(), re_dfastate_t::halt, re_dfastate_t::has_backref, re_dfastate_t::has_constraint, re_node_set::nelem, node, re_dfa_t::nodes, re_dfastate_t::nodes, NOT_SATISFY_PREV_CONSTRAINT, OP_BACK_REF, re_token_t::opr, re_free, re_malloc, re_node_set_init_copy(), re_node_set_remove_at(), REG_NOERROR, register_state(), and re_token_t::type.
Referenced by re_acquire_state_context().
static re_dfastate_t *internal_function create_ci_newstate (const re_dfa_t * dfa, const re_node_set * nodes, unsigned int hash) [static]
References re_dfastate_t::accept_mb, BE, CHARACTER, re_token_t::constraint, re_node_set::elems, END_OF_RE, re_dfastate_t::entrance_nodes, free_state(), re_dfastate_t::halt, re_dfastate_t::has_backref, re_dfastate_t::has_constraint, re_node_set::nelem, node, re_dfa_t::nodes, re_dfastate_t::nodes, OP_BACK_REF, re_free, re_node_set_init_copy(), REG_NOERROR, register_state(), and re_token_t::type.
Referenced by re_acquire_state().
static void free_state (re_dfastate_t * state) [static]
References re_dfastate_t::entrance_nodes, re_dfastate_t::inveclosure, re_dfastate_t::nodes, re_dfastate_t::non_eps_nodes, re_free, re_node_set_free, re_dfastate_t::trtable, and re_dfastate_t::word_trtable.
Referenced by create_cd_newstate(), create_ci_newstate(), and free_dfa_content().
static re_dfastate_t* internal_function re_acquire_state (reg_errcode_t * err, const re_dfa_t * dfa, const re_node_set * nodes) [static]
References re_state_table_entry::array, BE, calc_state_hash(), create_ci_newstate(), re_dfastate_t::hash, re_node_set::nelem, re_dfastate_t::nodes, re_state_table_entry::num, REG_ESPACE, REG_NOERROR, re_dfa_t::state_hash_mask, and re_dfa_t::state_table.
Referenced by add_epsilon_src_nodes(), check_arrival_add_next_nodes(), expand_bkref_cache(), merge_state_array(), and update_cur_sifted_state().
static re_dfastate_t* internal_function re_acquire_state_context (reg_errcode_t * err, const re_dfa_t * dfa, const re_node_set * nodes, unsigned int context) [static]
References re_state_table_entry::array, BE, calc_state_hash(), re_dfastate_t::context, create_cd_newstate(), re_dfastate_t::entrance_nodes, re_dfastate_t::hash, re_node_set::nelem, re_state_table_entry::num, REG_ESPACE, REG_NOERROR, re_dfa_t::state_hash_mask, and re_dfa_t::state_table.
Referenced by __attribute(), build_trtable(), check_arrival(), create_initial_state(), merge_state_with_log(), and transit_state_bkref().
static int internal_function re_dfa_add_node (re_dfa_t * dfa, re_token_t token) [static]
References BE, re_token_t::constraint, re_dfa_t::eclosures, re_dfa_t::edests, re_dfa_t::mb_cur_max, re_dfa_t::nexts, re_dfa_t::nodes, re_dfa_t::nodes_alloc, re_dfa_t::nodes_len, OP_PERIOD, re_dfa_t::org_indices, re_node_set_init_empty, re_realloc, and re_token_t::type.
Referenced by calc_first(), and duplicate_node().
static reg_errcode_t internal_function re_node_set_add_intersect (re_node_set * dest, const re_node_set * src1, const re_node_set * src2) [static]
References re_node_set::alloc, BE, re_node_set::elems, re_node_set::nelem, re_realloc, REG_ESPACE, and REG_NOERROR.
Referenced by add_epsilon_src_nodes(), and sub_epsilon_src_nodes().
static reg_errcode_t internal_function re_node_set_alloc (re_node_set * set, int size) [static]
References BE, re_malloc, REG_ESPACE, and REG_NOERROR.
Referenced by add_epsilon_src_nodes(), build_trtable(), calc_eclosure_iter(), check_arrival_expand_ecl(), and register_state().
static reg_errcode_t internal_function re_node_set_init_1 (re_node_set * set, int elem) [static]
References BE, re_malloc, REG_ESPACE, and REG_NOERROR.
Referenced by check_arrival(), expand_bkref_cache(), group_nodes_into_DFAstates(), link_nfa_nodes(), re_node_set_insert(), and sift_states_backward().
static reg_errcode_t internal_function re_node_set_init_2 (re_node_set * set, int elem1, int elem2) [static]
References BE, re_malloc, REG_ESPACE, and REG_NOERROR.
Referenced by link_nfa_nodes().
static reg_errcode_t internal_function re_node_set_init_copy (re_node_set * dest, const re_node_set * src) [static]
References re_node_set::alloc, BE, re_node_set::elems, re_node_set::nelem, re_malloc, re_node_set_init_empty, REG_ESPACE, and REG_NOERROR.
Referenced by check_arrival(), create_cd_newstate(), create_ci_newstate(), create_initial_state(), expand_bkref_cache(), group_nodes_into_DFAstates(), push_fail_stack(), re_node_set_init_union(), and sift_states_bkref().
static reg_errcode_t internal_function re_node_set_init_union (re_node_set * dest, const re_node_set * src1, const re_node_set * src2) [static]
References re_node_set::alloc, BE, re_node_set::elems, re_node_set::nelem, re_malloc, re_node_set_init_copy(), re_node_set_init_empty, REG_ESPACE, and REG_NOERROR.
Referenced by merge_state_array(), merge_state_with_log(), and transit_state_bkref().
static int internal_function re_node_set_insert (re_node_set * set, int elem) [static]
References BE, re_node_set_init_1(), re_realloc, and REG_NOERROR.
Referenced by build_sifted_states(), calc_eclosure_iter(), check_arrival_add_next_nodes(), check_arrival_expand_ecl_sub(), duplicate_node_closure(), expand_bkref_cache(), group_nodes_into_DFAstates(), proceed_next_node(), and sift_states_bkref().
static int internal_function re_node_set_insert_last (re_node_set * set, int elem) [static]
References BE, and re_realloc.
Referenced by calc_inveclosure(), and register_state().
static reg_errcode_t internal_function re_node_set_merge (re_node_set * dest, const re_node_set * src) [static]
References re_node_set::alloc, BE, re_node_set::elems, re_node_set::nelem, re_realloc, REG_ESPACE, and REG_NOERROR.
Referenced by add_epsilon_src_nodes(), build_trtable(), calc_eclosure_iter(), check_arrival(), check_arrival_add_next_nodes(), check_arrival_expand_ecl(), create_initial_state(), and expand_bkref_cache().
static void internal_function re_node_set_remove_at (re_node_set * set, int idx) [static]
Referenced by create_cd_newstate(), and sub_epsilon_src_nodes().
static reg_errcode_t internal_function re_string_allocate (re_string_t * pstr, const char * str, int len, int init_len, RE_TRANSLATE_TYPE trans, int icase, const re_dfa_t * dfa) [static]
References BE, re_dfa_t::mb_cur_max, re_string_t::mbs, re_string_t::mbs_allocated, re_string_construct_common(), re_string_realloc_buffers(), REG_NOERROR, re_string_t::valid_len, re_string_t::valid_raw_len, re_dfa_t::word_char, re_string_t::word_char, re_dfa_t::word_ops_used, and re_string_t::word_ops_used.
Referenced by re_search_internal().
static reg_errcode_t internal_function re_string_construct (re_string_t * pstr, const char * str, int len, RE_TRANSLATE_TYPE trans, int icase, const re_dfa_t * dfa) [static]
References BE, re_string_t::bufs_len, build_upper_buffer(), re_dfa_t::mb_cur_max, re_string_t::mbs, re_string_t::mbs_allocated, re_string_construct_common(), re_string_realloc_buffers(), re_string_translate_buffer(), REG_NOERROR, re_string_t::valid_len, and re_string_t::valid_raw_len.
Referenced by re_compile_internal().
static void internal_function re_string_construct_common (const char * str, int len, re_string_t * pstr, RE_TRANSLATE_TYPE trans, int icase, const re_dfa_t * dfa) [static]
References re_string_t::icase, re_dfa_t::is_utf8, re_string_t::is_utf8, re_string_t::len, re_dfa_t::map_notascii, re_string_t::map_notascii, re_dfa_t::mb_cur_max, re_string_t::mb_cur_max, re_string_t::mbs_allocated, re_string_t::raw_len, re_string_t::raw_mbs, re_string_t::raw_stop, re_string_t::stop, and re_string_t::trans.
Referenced by re_string_allocate(), and re_string_construct().
static unsigned int internal_function re_string_context_at (const re_string_t * input, int idx, int eflags) [static]
References BE, bitset_contain, CONTEXT_ENDBUF, CONTEXT_NEWLINE, CONTEXT_WORD, IS_NEWLINE, IS_WIDE_NEWLINE, IS_WIDE_WORD_CHAR, re_string_t::len, re_string_t::mb_cur_max, re_string_t::newline_anchor, re_string_byte_at, REG_NOTEOL, re_string_t::tip_context, re_string_t::word_char, and re_string_t::word_ops_used.
Referenced by __attribute(), check_arrival(), check_halt_state_context(), check_node_accept(), merge_state_with_log(), re_string_reconstruct(), transit_state(), and transit_state_bkref().
static void internal_function re_string_destruct (re_string_t * pstr) [static]
References re_string_t::mbs, re_string_t::mbs_allocated, and re_free.
Referenced by re_compile_internal(), and re_search_internal().
static reg_errcode_t internal_function re_string_realloc_buffers (re_string_t * pstr, int new_buf_len) [static]
References BE, re_string_t::bufs_len, re_string_t::mb_cur_max, re_string_t::mbs, re_string_t::mbs_allocated, re_realloc, REG_ESPACE, and REG_NOERROR.
Referenced by extend_buffers(), re_string_allocate(), and re_string_construct().
static reg_errcode_t internal_function re_string_reconstruct (re_string_t * pstr, int idx, int eflags) [static]
References BE, bitset_contain, build_upper_buffer(), CONTEXT_BEGBUF, CONTEXT_NEWLINE, CONTEXT_WORD, re_string_t::cur_idx, re_string_t::icase, IS_NEWLINE, re_string_t::is_utf8, IS_WIDE_NEWLINE, IS_WIDE_WORD_CHAR, re_string_t::len, re_string_t::mb_cur_max, re_string_t::mbs, re_string_t::mbs_allocated, re_string_t::newline_anchor, re_string_t::offsets_needed, re_string_t::raw_len, re_string_t::raw_mbs, re_string_t::raw_mbs_idx, re_string_t::raw_stop, re_string_context_at(), re_string_translate_buffer(), REG_NOERROR, REG_NOTBOL, re_string_t::stop, re_string_t::tip_context, re_string_t::trans, re_string_t::valid_len, re_string_t::valid_raw_len, re_string_t::word_char, and re_string_t::word_ops_used.
Referenced by re_search_internal().
static void internal_function re_string_translate_buffer (re_string_t * pstr) [static]
References re_string_t::bufs_len, re_string_t::len, re_string_t::mbs, re_string_t::raw_mbs, re_string_t::raw_mbs_idx, re_string_t::trans, re_string_t::valid_len, and re_string_t::valid_raw_len.
Referenced by extend_buffers(), re_string_construct(), and re_string_reconstruct().
static reg_errcode_t register_state (const re_dfa_t * dfa, re_dfastate_t * newstate, unsigned int hash) [static]
References re_state_table_entry::alloc, re_state_table_entry::array, BE, re_node_set::elems, re_dfastate_t::hash, IS_EPSILON_NODE, re_node_set::nelem, re_dfa_t::nodes, re_dfastate_t::nodes, re_dfastate_t::non_eps_nodes, re_state_table_entry::num, re_node_set_alloc(), re_node_set_insert_last(), re_realloc, REG_ESPACE, REG_NOERROR, re_dfa_t::state_hash_mask, re_dfa_t::state_table, and re_token_t::type.
Referenced by create_cd_newstate(), and create_ci_newstate().