CWB: mingw-libgnurx-2.5.1/regexec.c File Reference
regexec.c File Reference
Defines
#define STATE_NODE_CONTAINS(state, node) ((state) != NULL && re_node_set_contains (&(state)->nodes, node))
Functions
static reg_errcode_t match_ctx_init (re_match_context_t *cache, int eflags, int n) internal_function
static void match_ctx_clean (re_match_context_t *mctx) internal_function
static void match_ctx_free (re_match_context_t *cache) internal_function
static reg_errcode_t match_ctx_add_entry (re_match_context_t *cache, int node, int str_idx, int from, int to) internal_function
static int search_cur_bkref_entry (const re_match_context_t *mctx, int str_idx) internal_function
static reg_errcode_t match_ctx_add_subtop (re_match_context_t *mctx, int node, int str_idx) internal_function
static re_sub_match_last_t * match_ctx_add_sublast (re_sub_match_top_t *subtop, int node, int str_idx) internal_function
static void sift_ctx_init (re_sift_context_t *sctx, re_dfastate_t **sifted_sts, re_dfastate_t **limited_sts, int last_node, int last_str_idx) internal_function
static reg_errcode_t re_search_internal (const regex_t *preg, const char *string, int length, int start, int range, int stop, size_t nmatch, regmatch_t pmatch[], int eflags) internal_function
static int re_search_2_stub (struct re_pattern_buffer *bufp, const char *string1, int length1, const char *string2, int length2, int start, int range, struct re_registers *regs, int stop, int ret_len) internal_function
static int re_search_stub (struct re_pattern_buffer *bufp, const char *string, int length, int start, int range, int stop, struct re_registers *regs, int ret_len) internal_function
static unsigned re_copy_regs (struct re_registers *regs, regmatch_t *pmatch, int nregs, int regs_allocated) internal_function
static reg_errcode_t prune_impossible_nodes (re_match_context_t *mctx) internal_function
static int check_matching (re_match_context_t *mctx, int fl_longest_match, int *p_match_first) internal_function
static int check_halt_state_context (const re_match_context_t *mctx, const re_dfastate_t *state, int idx) internal_function
static void update_regs (const re_dfa_t *dfa, regmatch_t *pmatch, regmatch_t *prev_idx_match, int cur_node, int cur_idx, int nmatch) internal_function
static reg_errcode_t push_fail_stack (struct re_fail_stack_t *fs, int str_idx, int dest_node, int nregs, regmatch_t *regs, re_node_set *eps_via_nodes) internal_function
static reg_errcode_t set_regs (const regex_t *preg, const re_match_context_t *mctx, size_t nmatch, regmatch_t *pmatch, int fl_backtrack) internal_function
static reg_errcode_t free_fail_stack_return (struct re_fail_stack_t *fs) internal_function
static reg_errcode_t sift_states_backward (const re_match_context_t *mctx, re_sift_context_t *sctx) internal_function
static reg_errcode_t build_sifted_states (const re_match_context_t *mctx, re_sift_context_t *sctx, int str_idx, re_node_set *cur_dest) internal_function
static reg_errcode_t update_cur_sifted_state (const re_match_context_t *mctx, re_sift_context_t *sctx, int str_idx, re_node_set *dest_nodes) internal_function
static reg_errcode_t add_epsilon_src_nodes (const re_dfa_t *dfa, re_node_set *dest_nodes, const re_node_set *candidates) internal_function
static int check_dst_limits (const re_match_context_t *mctx, re_node_set *limits, int dst_node, int dst_idx, int src_node, int src_idx) internal_function
static int check_dst_limits_calc_pos_1 (const re_match_context_t *mctx, int boundaries, int subexp_idx, int from_node, int bkref_idx) internal_function
static int check_dst_limits_calc_pos (const re_match_context_t *mctx, int limit, int subexp_idx, int node, int str_idx, int bkref_idx) internal_function
static reg_errcode_t check_subexp_limits (const re_dfa_t *dfa, re_node_set *dest_nodes, const re_node_set *candidates, re_node_set *limits, struct re_backref_cache_entry *bkref_ents, int str_idx) internal_function
static reg_errcode_t sift_states_bkref (const re_match_context_t *mctx, re_sift_context_t *sctx, int str_idx, const re_node_set *candidates) internal_function
static reg_errcode_t merge_state_array (const re_dfa_t *dfa, re_dfastate_t **dst, re_dfastate_t **src, int num) internal_function
static re_dfastate_t * find_recover_state (reg_errcode_t *err, re_match_context_t *mctx) internal_function
static re_dfastate_t * transit_state (reg_errcode_t *err, re_match_context_t *mctx, re_dfastate_t *state) internal_function
static re_dfastate_t * merge_state_with_log (reg_errcode_t *err, re_match_context_t *mctx, re_dfastate_t *next_state) internal_function
static reg_errcode_t check_subexp_matching_top (re_match_context_t *mctx, re_node_set *cur_nodes, int str_idx) internal_function
static reg_errcode_t transit_state_bkref (re_match_context_t *mctx, const re_node_set *nodes) internal_function
static reg_errcode_t get_subexp (re_match_context_t *mctx, int bkref_node, int bkref_str_idx) internal_function
static reg_errcode_t get_subexp_sub (re_match_context_t *mctx, const re_sub_match_top_t *sub_top, re_sub_match_last_t *sub_last, int bkref_node, int bkref_str) internal_function
static int find_subexp_node (const re_dfa_t *dfa, const re_node_set *nodes, int subexp_idx, int type) internal_function
static reg_errcode_t check_arrival (re_match_context_t *mctx, state_array_t *path, int top_node, int top_str, int last_node, int last_str, int type) internal_function
static reg_errcode_t check_arrival_add_next_nodes (re_match_context_t *mctx, int str_idx, re_node_set *cur_nodes, re_node_set *next_nodes) internal_function
static reg_errcode_t check_arrival_expand_ecl (const re_dfa_t *dfa, re_node_set *cur_nodes, int ex_subexp, int type) internal_function
static reg_errcode_t check_arrival_expand_ecl_sub (const re_dfa_t *dfa, re_node_set *dst_nodes, int target, int ex_subexp, int type) internal_function
static reg_errcode_t expand_bkref_cache (re_match_context_t *mctx, re_node_set *cur_nodes, int cur_str, int subexp_num, int type) internal_function
static int build_trtable (const re_dfa_t *dfa, re_dfastate_t *state) internal_function
static int group_nodes_into_DFAstates (const re_dfa_t *dfa, const re_dfastate_t *state, re_node_set *states_node, bitset_t *states_ch) internal_function
static int check_node_accept (const re_match_context_t *mctx, const re_token_t *node, int idx) internal_function
static reg_errcode_t extend_buffers (re_match_context_t *mctx) internal_function
int regexec (regex_t *__restrict preg, const char *__restrict string, size_t nmatch, pmatch, int eflags) const
int re_match (struct re_pattern_buffer *bufp, const char *string, int length, int start, struct re_registers *regs)
int re_search (struct re_pattern_buffer *bufp, const char *string, int length, int start, int range, struct re_registers *regs)
int re_match_2 (struct re_pattern_buffer *bufp, const char *string1, int length1, const char *string2, int length2, int start, struct re_registers *regs, int stop)
int re_search_2 (struct re_pattern_buffer *bufp, const char *string1, int length1, const char *string2, int length2, int start, int range, struct re_registers *regs, int stop)
void re_set_registers (struct re_pattern_buffer *bufp, struct re_registers *regs, unsigned num_regs, regoff_t *starts, regoff_t *ends)
static reg_errcode_t re_search_internal (regex_t *preg, const char *string, int length, int start, int range, int stop, size_t nmatch, pmatch, int eflags) const
static re_dfastate_t * __attribute ((always_inline))
static int internal_function check_halt_node_context (const re_dfa_t *dfa, int node, unsigned int context)
static int internal_function proceed_next_node (const re_match_context_t *mctx, int nregs, regmatch_t *regs, int *pidx, int node, re_node_set *eps_via_nodes, struct re_fail_stack_t *fs)
static int internal_function pop_fail_stack (struct re_fail_stack_t *fs, int *pidx, int nregs, regmatch_t *regs, re_node_set *eps_via_nodes)
static reg_errcode_t
internal_function clean_state_log_if_needed (re_match_context_t *mctx, int next_state_log_idx)
static reg_errcode_t
internal_function sub_epsilon_src_nodes (const re_dfa_t *dfa, int node, re_node_set *dest_nodes, const re_node_set *candidates)
Define Documentation
#define STATE_NODE_CONTAINS (state, node) ((state) != NULL && re_node_set_contains (&(state)->nodes, node))
Referenced by build_sifted_states(), and sift_states_bkref().
Function Documentation
static re_dfastate_t* __attribute ((always_inline)) [inline, static]
References re_dfastate_t::entrance_nodes, re_dfastate_t::has_constraint, re_dfa_t::init_state, re_dfa_t::init_state_begbuf, re_dfa_t::init_state_nl, re_dfa_t::init_state_word, IS_BEGBUF_CONTEXT, IS_NEWLINE_CONTEXT, IS_ORDINARY_CONTEXT, IS_WORD_CONTEXT, re_acquire_state_context(), and re_string_context_at().
static reg_errcode_t internal_function add_epsilon_src_nodes (const re_dfa_t * dfa, re_node_set * dest_nodes, const re_node_set * candidates) [static]
References re_node_set::alloc, BE, re_node_set::elems, re_dfastate_t::inveclosure, re_dfa_t::inveclosures, re_node_set::nelem, re_acquire_state(), re_node_set_add_intersect(), re_node_set_alloc(), re_node_set_merge(), REG_ESPACE, and REG_NOERROR.
Referenced by update_cur_sifted_state().
static reg_errcode_t internal_function build_sifted_states (const re_match_context_t * mctx, re_sift_context_t * sctx, int str_idx, re_node_set * cur_dest) [static]
References BE, check_dst_limits(), check_node_accept(), re_match_context_t::dfa, re_node_set::elems, IS_EPSILON_NODE, re_sift_context_t::last_str_idx, re_sift_context_t::limits, re_node_set::nelem, re_dfa_t::nexts, re_dfa_t::nodes, re_dfastate_t::non_eps_nodes, re_node_set_insert(), REG_ESPACE, REG_NOERROR, re_sift_context_t::sifted_states, re_match_context_t::state_log, STATE_NODE_CONTAINS, and re_token_t::type.
Referenced by sift_states_backward().
static int internal_function build_trtable (const re_dfa_t * dfa, re_dfastate_t * state) [static]
References __libc_use_alloca, BE, bitset_contain, bitset_empty, bitset_merge(), BITSET_WORD_BITS, BITSET_WORDS, CONTEXT_NEWLINE, CONTEXT_WORD, re_dfa_t::eclosures, re_node_set::elems, group_nodes_into_DFAstates(), re_dfa_t::mb_cur_max, re_node_set::nelem, NEWLINE_CHAR, re_dfa_t::nexts, re_acquire_state_context(), re_malloc, re_node_set_alloc(), re_node_set_empty, re_node_set_free, re_node_set_merge(), REG_NOERROR, SBC_MAX, re_dfastate_t::trtable, re_dfa_t::word_char, and re_dfastate_t::word_trtable.
Referenced by transit_state().
static reg_errcode_t internal_function check_arrival (re_match_context_t * mctx, state_array_t * path, int top_node, int top_str, int last_node, int last_str, int type) [static]
References state_array_t::alloc, state_array_t::array, BE, check_arrival_add_next_nodes(), check_arrival_expand_ecl(), re_string_t::cur_idx, re_match_context_t::dfa, re_match_context_t::eflags, expand_bkref_cache(), re_dfastate_t::has_backref, re_token_t::idx, re_match_context_t::input, re_match_context_t::max_mb_elem_len, re_node_set::nelem, state_array_t::next_idx, re_dfastate_t::nodes, re_dfa_t::nodes, re_dfastate_t::non_eps_nodes, re_token_t::opr, re_acquire_state_context(), re_node_set_empty, re_node_set_free, re_node_set_init_1(), re_node_set_init_copy(), re_node_set_init_empty, re_node_set_merge(), re_realloc, re_string_context_at(), REG_ESPACE, REG_NOERROR, REG_NOMATCH, and re_match_context_t::state_log.
Referenced by get_subexp(), and get_subexp_sub().
static reg_errcode_t internal_function check_arrival_add_next_nodes (re_match_context_t * mctx, int str_idx, re_node_set * cur_nodes, re_node_set * next_nodes) [static]
References BE, check_node_accept(), re_match_context_t::dfa, re_node_set::elems, re_match_context_t::input, IS_EPSILON_NODE, re_node_set::nelem, re_dfa_t::nexts, re_dfastate_t::nodes, re_dfa_t::nodes, re_acquire_state(), re_node_set_empty, re_node_set_free, re_node_set_init_empty, re_node_set_insert(), re_node_set_merge(), REG_ESPACE, REG_NOERROR, re_match_context_t::state_log, and re_token_t::type.
Referenced by check_arrival().
static reg_errcode_t internal_function check_arrival_expand_ecl (const re_dfa_t * dfa, re_node_set * cur_nodes, int ex_subexp, int type) [static]
References BE, check_arrival_expand_ecl_sub(), re_dfa_t::eclosures, re_node_set::elems, find_subexp_node(), re_node_set::nelem, re_node_set_alloc(), re_node_set_free, re_node_set_merge(), and REG_NOERROR.
Referenced by check_arrival(), and expand_bkref_cache().
static reg_errcode_t internal_function check_arrival_expand_ecl_sub (const re_dfa_t * dfa, re_node_set * dst_nodes, int target, int ex_subexp, int type) [static]
References BE, re_dfa_t::edests, re_node_set::elems, re_token_t::idx, re_node_set::nelem, re_dfa_t::nodes, re_token_t::opr, re_node_set_insert(), REG_ESPACE, REG_NOERROR, and re_token_t::type.
Referenced by check_arrival_expand_ecl().
static int internal_function check_dst_limits (const re_match_context_t * mctx, re_node_set * limits, int dst_node, int dst_idx, int src_node, int src_idx) [static]
References re_match_context_t::bkref_ents, check_dst_limits_calc_pos(), re_match_context_t::dfa, re_node_set::elems, re_token_t::idx, re_node_set::nelem, re_backref_cache_entry::node, re_dfa_t::nodes, re_token_t::opr, and search_cur_bkref_entry().
Referenced by build_sifted_states(), and sift_states_bkref().
static int internal_function check_dst_limits_calc_pos (const re_match_context_t * mctx, int limit, int subexp_idx, int node, int str_idx, int bkref_idx) [static]
References re_match_context_t::bkref_ents, check_dst_limits_calc_pos_1(), re_backref_cache_entry::subexp_from, and re_backref_cache_entry::subexp_to.
Referenced by check_dst_limits().
static int internal_function check_dst_limits_calc_pos_1 (const re_match_context_t * mctx, int boundaries, int subexp_idx, int from_node, int bkref_idx) [static]
References BITSET_WORD_BITS, re_match_context_t::bkref_ents, re_match_context_t::dfa, re_dfa_t::eclosures, re_dfa_t::edests, re_node_set::elems, re_backref_cache_entry::eps_reachable_subexps_map, re_token_t::idx, re_backref_cache_entry::more, re_node_set::nelem, re_backref_cache_entry::node, node, re_dfa_t::nodes, OP_BACK_REF, re_token_t::opr, and re_token_t::type.
Referenced by check_dst_limits_calc_pos().
static int internal_function check_halt_node_context (const re_dfa_t * dfa, int node, unsigned int context) [static]
References re_token_t::constraint, END_OF_RE, re_dfa_t::nodes, NOT_SATISFY_NEXT_CONSTRAINT, and re_token_t::type.
Referenced by check_halt_state_context().
static int internal_function check_halt_state_context (const re_match_context_t * mctx, const re_dfastate_t * state, int idx) [static]
References check_halt_node_context(), re_match_context_t::dfa, re_match_context_t::eflags, re_node_set::elems, re_dfastate_t::halt, re_match_context_t::input, re_node_set::nelem, re_dfastate_t::nodes, and re_string_context_at().
Referenced by check_matching(), prune_impossible_nodes(), and re_search_internal().
static int internal_function check_matching (re_match_context_t * mctx, int fl_longest_match, int * p_match_first) [static]
References BE, re_string_t::bufs_len, check_halt_state_context(), check_subexp_matching_top(), re_match_context_t::dfa, extend_buffers(), find_recover_state(), re_dfastate_t::halt, re_dfastate_t::has_backref, re_dfastate_t::has_constraint, re_match_context_t::input, re_string_t::len, merge_state_with_log(), re_dfa_t::nbackref, re_dfastate_t::nodes, re_string_cur_idx, re_string_eoi, REG_ESPACE, REG_NOERROR, re_match_context_t::state_log, transit_state(), transit_state_bkref(), and re_string_t::valid_len.
Referenced by re_search_internal().
static int internal_function check_node_accept (const re_match_context_t * mctx, const re_token_t * node, int idx) [static]
References bitset_contain, re_token_t::c, CHARACTER, re_token_t::constraint, re_match_context_t::dfa, re_match_context_t::eflags, re_match_context_t::input, NOT_SATISFY_NEXT_CONSTRAINT, OP_PERIOD, re_token_t::opr, RE_DOT_NEWLINE, RE_DOT_NOT_NULL, re_string_byte_at, re_string_context_at(), re_token_t::sbcset, SIMPLE_BRACKET, re_dfa_t::syntax, and re_token_t::type.
Referenced by build_sifted_states(), check_arrival_add_next_nodes(), and proceed_next_node().
static reg_errcode_t internal_function check_subexp_limits (const re_dfa_t * dfa, re_node_set * dest_nodes, const re_node_set * candidates, re_node_set * limits, struct re_backref_cache_entry * bkref_ents, int str_idx) [static]
References BE, re_dfa_t::eclosures, re_node_set::elems, re_token_t::idx, re_dfa_t::inveclosures, re_node_set::nelem, node, re_backref_cache_entry::node, re_dfa_t::nodes, re_token_t::opr, REG_NOERROR, re_backref_cache_entry::str_idx, sub_epsilon_src_nodes(), re_backref_cache_entry::subexp_from, re_backref_cache_entry::subexp_to, and re_token_t::type.
Referenced by update_cur_sifted_state().
static reg_errcode_t internal_function check_subexp_matching_top (re_match_context_t * mctx, re_node_set * cur_nodes, int str_idx) [static]
References BE, BITSET_WORD_BITS, re_match_context_t::dfa, re_node_set::elems, re_token_t::idx, match_ctx_add_subtop(), re_node_set::nelem, node, re_dfa_t::nodes, re_token_t::opr, REG_NOERROR, re_token_t::type, and re_dfa_t::used_bkref_map.
Referenced by check_matching(), merge_state_with_log(), and transit_state_bkref().
static reg_errcode_t internal_function clean_state_log_if_needed (re_match_context_t * mctx, int next_state_log_idx) [static]
References BE, re_string_t::bufs_len, extend_buffers(), re_match_context_t::input, re_string_t::len, REG_NOERROR, re_match_context_t::state_log, re_match_context_t::state_log_top, and re_string_t::valid_len.
Referenced by get_subexp(), and get_subexp_sub().
static reg_errcode_t internal_function expand_bkref_cache (re_match_context_t * mctx, re_node_set * cur_nodes, int cur_str, int subexp_num, int type) [static]
References BE, re_match_context_t::bkref_ents, check_arrival_expand_ecl(), re_match_context_t::dfa, re_dfa_t::edests, re_node_set::elems, re_backref_cache_entry::more, re_dfa_t::nexts, re_backref_cache_entry::node, re_dfastate_t::nodes, re_acquire_state(), re_node_set_free, re_node_set_init_1(), re_node_set_init_copy(), re_node_set_insert(), re_node_set_merge(), REG_ESPACE, REG_NOERROR, search_cur_bkref_entry(), re_match_context_t::state_log, re_backref_cache_entry::subexp_from, and re_backref_cache_entry::subexp_to.
Referenced by check_arrival().
static reg_errcode_t internal_function extend_buffers (re_match_context_t * mctx) [static]
References BE, re_string_t::bufs_len, build_upper_buffer(), re_string_t::icase, re_match_context_t::input, re_string_t::mb_cur_max, re_realloc, re_string_realloc_buffers(), re_string_translate_buffer(), REG_ESPACE, REG_NOERROR, re_match_context_t::state_log, and re_string_t::trans.
Referenced by check_matching(), clean_state_log_if_needed(), and get_subexp().
re_dfastate_t *internal_function find_recover_state (reg_errcode_t * err, re_match_context_t * mctx) [static]
References re_match_context_t::input, merge_state_with_log(), re_string_cur_idx, re_string_skip_bytes, REG_NOERROR, re_match_context_t::state_log, and re_match_context_t::state_log_top.
Referenced by check_matching().
static int internal_function find_subexp_node (const re_dfa_t * dfa, const re_node_set * nodes, int subexp_idx, int type) [static]
References re_node_set::elems, re_token_t::idx, re_node_set::nelem, node, re_dfa_t::nodes, re_token_t::opr, and re_token_t::type.
Referenced by check_arrival_expand_ecl(), and get_subexp().
static reg_errcode_t internal_function free_fail_stack_return (struct re_fail_stack_t * fs) [static]
References re_fail_stack_ent_t::eps_via_nodes, re_fail_stack_t::num, re_free, re_node_set_free, REG_NOERROR, re_fail_stack_ent_t::regs, and re_fail_stack_t::stack.
static reg_errcode_t internal_function get_subexp (re_match_context_t * mctx, int bkref_node, int bkref_str_idx) [static]
References BE, re_match_context_t::bkref_ents, buf, check_arrival(), clean_state_log_if_needed(), re_match_context_t::dfa, extend_buffers(), find_subexp_node(), get_subexp_sub(), re_token_t::idx, re_match_context_t::input, re_sub_match_top_t::lasts, re_string_t::len, match_ctx_add_sublast(), re_backref_cache_entry::more, re_sub_match_top_t::nlasts, re_sub_match_top_t::node, re_backref_cache_entry::node, re_dfastate_t::nodes, re_dfa_t::nodes, re_match_context_t::nsub_tops, re_token_t::opr, re_sub_match_top_t::path, re_string_get_buffer, REG_ESPACE, REG_NOERROR, REG_NOMATCH, search_cur_bkref_entry(), re_match_context_t::state_log, re_sub_match_last_t::str_idx, re_sub_match_top_t::str_idx, re_match_context_t::sub_tops, and re_string_t::valid_len.
Referenced by transit_state_bkref().
static reg_errcode_t internal_function get_subexp_sub (re_match_context_t * mctx, const re_sub_match_top_t * sub_top, re_sub_match_last_t * sub_last, int bkref_node, int bkref_str) [static]
References BE, check_arrival(), clean_state_log_if_needed(), match_ctx_add_entry(), re_sub_match_last_t::node, re_sub_match_last_t::path, REG_NOERROR, re_sub_match_top_t::str_idx, and re_sub_match_last_t::str_idx.
Referenced by get_subexp().
static int internal_function group_nodes_into_DFAstates (const re_dfa_t * dfa, const re_dfastate_t * state, re_node_set * states_node, bitset_t * states_ch) [static]
References BE, bitset_clear, bitset_contain, bitset_copy, bitset_empty, bitset_merge(), bitset_set, bitset_set_all, BITSET_WORDS, re_token_t::c, CHARACTER, re_token_t::constraint, re_node_set::elems, re_dfa_t::mb_cur_max, re_node_set::nelem, NEWLINE_CHAR, NEXT_ENDBUF_CONSTRAINT, NEXT_NEWLINE_CONSTRAINT, NEXT_NOTWORD_CONSTRAINT, NEXT_WORD_CONSTRAINT, node, re_dfa_t::nodes, re_dfastate_t::nodes, OP_PERIOD, re_token_t::opr, RE_DOT_NEWLINE, RE_DOT_NOT_NULL, re_node_set_free, re_node_set_init_1(), re_node_set_init_copy(), re_node_set_insert(), REG_NOERROR, re_dfa_t::sb_char, re_token_t::sbcset, SIMPLE_BRACKET, re_dfa_t::syntax, re_token_t::type, re_dfa_t::word_char, and re_token_t::word_char.
Referenced by build_trtable().
static reg_errcode_t internal_function match_ctx_add_entry (re_match_context_t * cache, int node, int str_idx, int from, int to) [static]
References re_match_context_t::abkref_ents, BE, re_match_context_t::bkref_ents, re_backref_cache_entry::eps_reachable_subexps_map, re_match_context_t::max_mb_elem_len, re_backref_cache_entry::more, re_match_context_t::nbkref_ents, re_backref_cache_entry::node, re_free, re_realloc, REG_ESPACE, REG_NOERROR, re_backref_cache_entry::str_idx, re_backref_cache_entry::subexp_from, and re_backref_cache_entry::subexp_to.
Referenced by get_subexp_sub().
static re_sub_match_last_t *internal_function match_ctx_add_sublast (re_sub_match_top_t * subtop, int node, int str_idx) [static]
References re_sub_match_top_t::alasts, BE, re_sub_match_top_t::lasts, re_sub_match_top_t::nlasts, re_sub_match_last_t::node, re_realloc, and re_sub_match_last_t::str_idx.
Referenced by get_subexp().
static reg_errcode_t internal_function match_ctx_add_subtop (re_match_context_t * mctx, int node, int str_idx) [static]
References re_match_context_t::asub_tops, BE, re_sub_match_top_t::node, re_match_context_t::nsub_tops, re_realloc, REG_ESPACE, REG_NOERROR, re_sub_match_top_t::str_idx, and re_match_context_t::sub_tops.
Referenced by check_subexp_matching_top().
static void internal_function match_ctx_clean (re_match_context_t * mctx) [static]
References state_array_t::array, last, re_sub_match_top_t::lasts, re_match_context_t::nbkref_ents, re_sub_match_top_t::nlasts, re_match_context_t::nsub_tops, re_sub_match_top_t::path, re_sub_match_last_t::path, re_free, and re_match_context_t::sub_tops.
Referenced by match_ctx_free(), and re_search_internal().
static void internal_function match_ctx_free (re_match_context_t * cache) [static]
References re_match_context_t::bkref_ents, match_ctx_clean(), re_free, and re_match_context_t::sub_tops.
Referenced by re_search_internal().
static reg_errcode_t internal_function match_ctx_init (re_match_context_t * cache, int eflags, int n) [static]
References re_match_context_t::abkref_ents, re_match_context_t::asub_tops, BE, re_match_context_t::bkref_ents, re_match_context_t::eflags, re_match_context_t::match_last, re_match_context_t::max_mb_elem_len, re_malloc, REG_ESPACE, REG_NOERROR, and re_match_context_t::sub_tops.
Referenced by re_search_internal().
static reg_errcode_t internal_function merge_state_array (const re_dfa_t * dfa, re_dfastate_t ** dst, re_dfastate_t ** src, int num) [static]
References BE, re_acquire_state(), re_node_set_free, re_node_set_init_union(), and REG_NOERROR.
Referenced by prune_impossible_nodes(), and sift_states_bkref().
re_dfastate_t *internal_function merge_state_with_log (reg_errcode_t * err, re_match_context_t * mctx, re_dfastate_t * next_state) [static]
References BE, check_subexp_matching_top(), re_match_context_t::dfa, re_match_context_t::eflags, re_dfastate_t::entrance_nodes, re_dfastate_t::has_backref, re_match_context_t::input, re_dfa_t::nbackref, re_dfastate_t::nodes, re_acquire_state_context(), re_node_set_free, re_node_set_init_union(), re_string_context_at(), re_string_cur_idx, REG_NOERROR, re_match_context_t::state_log, re_match_context_t::state_log_top, and transit_state_bkref().
Referenced by check_matching(), and find_recover_state().
static int internal_function pop_fail_stack (struct re_fail_stack_t * fs, int * pidx, int nregs, regmatch_t * regs, re_node_set * eps_via_nodes) [static]
References re_fail_stack_ent_t::eps_via_nodes, re_fail_stack_ent_t::idx, re_fail_stack_ent_t::node, re_fail_stack_t::num, re_free, re_node_set_free, re_fail_stack_ent_t::regs, and re_fail_stack_t::stack.
static int internal_function proceed_next_node (const re_match_context_t * mctx, int nregs, regmatch_t * regs, int * pidx, int node, re_node_set * eps_via_nodes, struct re_fail_stack_t * fs) [static]
References BE, buf, check_node_accept(), re_match_context_t::dfa, re_dfa_t::edests, re_node_set::elems, re_token_t::idx, re_match_context_t::input, IS_EPSILON_NODE, re_match_context_t::match_last, re_node_set::nelem, re_dfa_t::nexts, re_dfastate_t::nodes, re_dfa_t::nodes, OP_BACK_REF, re_token_t::opr, push_fail_stack(), re_node_set_empty, re_node_set_insert(), re_string_get_buffer, regmatch_t::rm_eo, regmatch_t::rm_so, re_match_context_t::state_log, and re_token_t::type.
static reg_errcode_t prune_impossible_nodes (re_match_context_t * mctx) [static]
References BE, check_halt_state_context(), re_sift_context_t::limits, merge_state_array(), re_dfa_t::nbackref, re_free, re_malloc, re_node_set_free, REG_ESPACE, REG_NOERROR, REG_NOMATCH, sift_ctx_init(), and sift_states_backward().
Referenced by re_search_internal().
static reg_errcode_t internal_function push_fail_stack (struct re_fail_stack_t * fs, int str_idx, int dest_node, int nregs, regmatch_t * regs, re_node_set * eps_via_nodes) [static]
References re_fail_stack_t::alloc, re_fail_stack_ent_t::eps_via_nodes, re_fail_stack_ent_t::idx, re_fail_stack_ent_t::node, re_fail_stack_t::num, re_state_table_entry::num, re_malloc, re_node_set_init_copy(), REG_ESPACE, re_fail_stack_ent_t::regs, and re_fail_stack_t::stack.
Referenced by proceed_next_node().
static unsigned re_copy_regs (struct re_registers * regs, regmatch_t * pmatch, int nregs, int regs_allocated) [static]
References BE, re_malloc, re_realloc, REGS_FIXED, REGS_REALLOCATE, REGS_UNALLOCATED, regmatch_t::rm_eo, and regmatch_t::rm_so.
Referenced by re_search_stub().
int re_match (struct re_pattern_buffer * bufp, const char * string, int length, int start, struct re_registers * regs)
References re_search_stub().
int re_match_2 (struct re_pattern_buffer * bufp, const char * string1, int length1, const char * string2, int length2, int start, struct re_registers * regs, int stop)
References re_search_2_stub().
int re_search (struct re_pattern_buffer * bufp, const char * string, int length, int start, int range, struct re_registers * regs)
References re_search_stub().
int re_search_2 (struct re_pattern_buffer * bufp, const char * string1, int length1, const char * string2, int length2, int start, int range, struct re_registers * regs, int stop)
References re_search_2_stub().
static int re_search_2_stub (struct re_pattern_buffer * bufp, const char * string1, int length1, const char * string2, int length2, int start, int range, struct re_registers * regs, int stop, int ret_len) [static]
References __mempcpy, BE, re_free, re_malloc, and re_search_stub().
Referenced by re_match_2(), and re_search_2().
static reg_errcode_t re_search_internal (regex_t * preg, const char * string, int length, int start, int range, int stop, size_t nmatch, pmatch , int eflags) const [static]
References BE, re_string_t::bufs_len, check_halt_state_context(), check_matching(), CONTEXT_BEGBUF, CONTEXT_NEWLINE, re_match_context_t::dfa, re_dfa_t::has_mb_node, re_dfa_t::has_plural_match, re_dfa_t::init_state, re_dfa_t::init_state_begbuf, re_dfa_t::init_state_nl, re_dfa_t::init_state_word, re_match_context_t::input, re_match_context_t::last_node, match_ctx_clean(), match_ctx_free(), match_ctx_init(), re_match_context_t::match_last, re_match_context_t::max_mb_elem_len, re_dfa_t::mb_cur_max, re_dfa_t::nbackref, re_match_context_t::nbkref_ents, re_node_set::nelem, re_string_t::newline_anchor, re_dfastate_t::nodes, re_dfa_t::nodes_len, re_string_t::offsets_needed, prune_impossible_nodes(), re_string_t::raw_mbs_idx, re_string_t::raw_stop, re_free, RE_ICASE, re_malloc, re_string_allocate(), re_string_byte_at, re_string_destruct(), re_string_first_byte, re_string_reconstruct(), RE_TRANSLATE_TYPE, REG_ESPACE, REG_NOERROR, REG_NOMATCH, REG_NOTBOL, regmatch_t::rm_eo, regmatch_t::rm_so, set_regs(), re_match_context_t::state_log, re_match_context_t::state_log_top, re_string_t::stop, re_dfa_t::subexp_map, re_string_t::tip_context, re_string_t::valid_len, and re_string_t::valid_raw_len.
static reg_errcode_t re_search_internal (const regex_t * preg, const char * string, int length, int start, int range, int stop, size_t nmatch, regmatch_t pmatch[], int eflags) [static]
Referenced by re_search_stub(), and regexec().
static int re_search_stub (struct re_pattern_buffer * bufp, const char * string, int length, int start, int range, int stop, struct re_registers * regs, int ret_len) [static]
References __libc_lock_lock, __libc_lock_unlock, BE, re_registers::num_regs, re_compile_fastmap(), re_copy_regs(), re_free, re_malloc, re_search_internal(), REG_NOERROR, REG_NOTBOL, REG_NOTEOL, REGS_FIXED, REGS_UNALLOCATED, regmatch_t::rm_eo, and regmatch_t::rm_so.
Referenced by re_match(), re_search(), and re_search_2_stub().
void re_set_registers (struct re_pattern_buffer * bufp, struct re_registers * regs, unsigned num_regs, regoff_t * starts, regoff_t * ends)
References re_registers::end, re_registers::num_regs, REGS_REALLOCATE, REGS_UNALLOCATED, and re_registers::start.
int regexec (regex_t *__restrict preg, const char *__restrict string, size_t nmatch, pmatch , int eflags) const
References __libc_lock_lock, __libc_lock_unlock, re_search_internal(), REG_BADPAT, REG_NOERROR, REG_NOTBOL, REG_NOTEOL, REG_STARTEND, regmatch_t::rm_eo, and regmatch_t::rm_so.
static int internal_function search_cur_bkref_entry (const re_match_context_t * mctx, int str_idx) [static]
References re_match_context_t::bkref_ents, last, left, re_match_context_t::nbkref_ents, right, and re_backref_cache_entry::str_idx.
Referenced by check_dst_limits(), expand_bkref_cache(), get_subexp(), and sift_states_bkref().
static reg_errcode_t internal_function set_regs (const regex_t * preg, const re_match_context_t * mctx, size_t nmatch, regmatch_t * pmatch, int fl_backtrack) [static]
References re_pattern_buffer::buffer, re_fail_stack_ent_t::eps_via_nodes, and re_fail_stack_ent_t::idx.
Referenced by re_search_internal().
static void internal_function sift_ctx_init (re_sift_context_t * sctx, re_dfastate_t ** sifted_sts, re_dfastate_t ** limited_sts, int last_node, int last_str_idx) [static]
References re_sift_context_t::last_node, re_sift_context_t::last_str_idx, re_sift_context_t::limited_states, re_sift_context_t::limits, re_node_set_init_empty, and re_sift_context_t::sifted_states.
Referenced by prune_impossible_nodes().
static reg_errcode_t internal_function sift_states_backward (const re_match_context_t * mctx, re_sift_context_t * sctx) [static]
References BE, build_sifted_states(), re_sift_context_t::last_node, re_sift_context_t::last_str_idx, re_match_context_t::max_mb_elem_len, re_node_set_empty, re_node_set_free, re_node_set_init_1(), REG_NOERROR, re_sift_context_t::sifted_states, re_match_context_t::state_log, and update_cur_sifted_state().
Referenced by prune_impossible_nodes(), and sift_states_bkref().
static reg_errcode_t internal_function sift_states_bkref (const re_match_context_t * mctx, re_sift_context_t * sctx, int str_idx, const re_node_set * candidates) [static]
References BE, re_match_context_t::bkref_ents, check_dst_limits(), re_match_context_t::dfa, re_dfa_t::edests, re_node_set::elems, re_sift_context_t::last_node, re_sift_context_t::last_str_idx, re_sift_context_t::limited_states, re_sift_context_t::limits, merge_state_array(), re_backref_cache_entry::more, re_node_set::nelem, re_dfa_t::nexts, re_backref_cache_entry::node, node, re_dfa_t::nodes, OP_BACK_REF, re_node_set_free, re_node_set_init_copy(), re_node_set_insert(), re_node_set_remove, REG_ESPACE, REG_NOERROR, search_cur_bkref_entry(), sift_states_backward(), re_sift_context_t::sifted_states, STATE_NODE_CONTAINS, re_backref_cache_entry::subexp_from, re_backref_cache_entry::subexp_to, and re_token_t::type.
Referenced by update_cur_sifted_state().
static reg_errcode_t internal_function sub_epsilon_src_nodes (const re_dfa_t * dfa, int node, re_node_set * dest_nodes, const re_node_set * candidates) [static]
References BE, re_dfa_t::edests, re_node_set::elems, re_fail_stack_ent_t::idx, re_dfa_t::inveclosures, IS_EPSILON_NODE, re_node_set::nelem, re_dfa_t::nodes, re_node_set_add_intersect(), re_node_set_free, re_node_set_init_empty, re_node_set_remove_at(), REG_NOERROR, and re_token_t::type.
Referenced by check_subexp_limits().
static re_dfastate_t *internal_function transit_state (reg_errcode_t * err, re_match_context_t * mctx, re_dfastate_t * state) [static]
References re_dfastate_t::accept_mb, BE, build_trtable(), re_match_context_t::dfa, re_match_context_t::eflags, re_match_context_t::input, IS_WORD_CONTEXT, re_string_context_at(), re_string_cur_idx, re_string_fetch_byte, REG_ESPACE, REG_NOERROR, SBC_MAX, re_dfastate_t::trtable, and re_dfastate_t::word_trtable.
Referenced by check_matching().
static reg_errcode_t internal_function transit_state_bkref (re_match_context_t * mctx, const re_node_set * nodes) [static]
References BE, re_match_context_t::bkref_ents, check_subexp_matching_top(), re_token_t::constraint, re_match_context_t::dfa, re_dfa_t::eclosures, re_dfa_t::edests, re_match_context_t::eflags, re_node_set::elems, re_dfastate_t::entrance_nodes, get_subexp(), re_match_context_t::input, re_match_context_t::nbkref_ents, re_node_set::nelem, re_dfa_t::nexts, re_backref_cache_entry::node, node, re_dfastate_t::nodes, re_dfa_t::nodes, NOT_SATISFY_NEXT_CONSTRAINT, OP_BACK_REF, re_acquire_state_context(), re_node_set_free, re_node_set_init_union(), re_string_context_at(), re_string_cur_idx, REG_NOERROR, re_match_context_t::state_log, re_backref_cache_entry::str_idx, re_backref_cache_entry::subexp_from, re_backref_cache_entry::subexp_to, and re_token_t::type.
Referenced by check_matching(), and merge_state_with_log().
static reg_errcode_t internal_function update_cur_sifted_state (const re_match_context_t * mctx, re_sift_context_t * sctx, int str_idx, re_node_set * dest_nodes) [static]
References add_epsilon_src_nodes(), BE, re_match_context_t::bkref_ents, check_subexp_limits(), re_match_context_t::dfa, re_dfastate_t::has_backref, re_sift_context_t::limits, re_node_set::nelem, re_dfastate_t::nodes, re_acquire_state(), REG_NOERROR, sift_states_bkref(), re_sift_context_t::sifted_states, and re_match_context_t::state_log.
Referenced by sift_states_backward().
static void internal_function update_regs (const re_dfa_t * dfa, regmatch_t * pmatch, regmatch_t * prev_idx_match, int cur_node, int cur_idx, int nmatch) [static]
References re_token_t::idx, re_dfa_t::nodes, re_token_t::opr, re_token_t::opt_subexp, regmatch_t::rm_eo, regmatch_t::rm_so, and re_token_t::type.