CWB: cqp/targets.c File Reference
targets.c File Reference
#include "../cl/globals.h"
#include <math.h>
#include "../cl/macros.h"
#include "../cl/attributes.h"
#include "corpmanag.h"
#include "eval.h"
#include "options.h"
#include "output.h"
#include "ranges.h"
#include "cqp.h"
#include "targets.h"
Functions
SearchStrategy string_to_strategy (char *s)
int set_target (CorpusList *corp, FieldType t_id, FieldType s_id)
int evaluate_target (CorpusList *corp, FieldType t_id, FieldType base, int inclusive, SearchStrategy strategy, Constrainttree constr, enum ctxtdir direction, int units, char *attr_name)
int evaluate_subset (CorpusList *cl, FieldType the_field, Constrainttree constr)
Function Documentation
int evaluate_subset (CorpusList * cl, FieldType the_field, Constrainttree constr)
References cqp, cqpmessage(), eval_bool(), EvaluationIsRunning, install_signal_handler(), KeywordField, cl::keywords, line, MatchEndField, MatchField, NoField, progress_bar, progress_bar_message(), progress_bar_percentage(), cl::range, RangeSetop(), RReduce, cl::size, SUB, TargetField, cl::targets, TEMP, cl::type, Warning, and which_app.
Referenced by do_subset().
int evaluate_target (CorpusList * corp, FieldType t_id, FieldType base, int inclusive, SearchStrategy strategy, Constrainttree constr, enum ctxtdir direction, int units, char * attr_name)
References ATT_POS, ATT_STRUC, ctxtsp::attrib, calculate_ranges(), CheckForInterrupts(), cl_calloc(), cl_free, cl::corpus, cqp, cqpmessage(), DEFAULT_ATT_NAME, ctxtsp::direction, Error, eval_bool(), EvaluationIsRunning, False, find_attribute(), install_signal_handler(), KeywordField, cl::keywords, left, line, MatchEndField, MatchField, MAX, cl::mother_name, progress_bar, progress_bar_clear_line(), progress_bar_message(), progress_bar_percentage(), cl::range, RangeSort(), right, SearchFarthest, SearchLeftmost, SearchNearest, SearchRightmost, ctxtsp::size, cl::size, structure, TargetField, cl::targets, touch_corpus(), ctxtsp::type, Warning, which_app, and word.
Referenced by do_set_complex_target().
int set_target (CorpusList * corp, FieldType t_id, FieldType s_id)
References cl_free, cl_malloc(), cqpmessage(), Error, KeywordField, cl::keywords, MatchEndField, MatchField, cl::name, NoField, cl::range, RangeSort(), cl::size, TargetField, cl::targets, and touch_corpus().
Referenced by do_set_target().
SearchStrategy string_to_strategy (char * s)
References cqpmessage(), SearchFarthest, SearchLeftmost, SearchNearest, SearchNone, SearchRightmost, and Warning.